name = "afonsojramos-me"
main = "./dist/_worker.js/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-25"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[env.production]
name = "afonsojramos-me"
route = { pattern = "afonsojramos.me", custom_domain = true }

[env.preview]
name = "afonsojramos-me-preview"
