// Generated by scripts/update-contributions.ts — do not edit by hand.
// Add repositories to scripts/contributions-blacklist.json to hide them.
export type Contribution = {
  repository: string;
  url: string;
  stars: number;
  mergedPullRequests: number;
  description?: string;
};

export const contributions: Contribution[] = [
  {
    repository: "vercel/next.js",
    url: "https://github.com/vercel/next.js",
    stars: 141776,
    mergedPullRequests: 1,
    description: "The React Framework",
  },
  {
    repository: "microsoft/TypeScript",
    url: "https://github.com/microsoft/TypeScript",
    stars: 110163,
    mergedPullRequests: 1,
    description: "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
  },
  {
    repository: "axios/axios",
    url: "https://github.com/axios/axios",
    stars: 109215,
    mergedPullRequests: 1,
    description: "Promise based HTTP client for the browser and node.js",
  },
  {
    repository: "facebook/docusaurus",
    url: "https://github.com/facebook/docusaurus",
    stars: 65925,
    mergedPullRequests: 1,
    description: "Easy to maintain open source documentation websites.",
  },
  {
    repository: "DefinitelyTyped/DefinitelyTyped",
    url: "https://github.com/DefinitelyTyped/DefinitelyTyped",
    stars: 51371,
    mergedPullRequests: 1,
    description: "The repository for high quality TypeScript type definitions.",
  },
  {
    repository: "files-community/Files",
    url: "https://github.com/files-community/Files",
    stars: 44628,
    mergedPullRequests: 1,
    description: "A modern file manager that helps users organize their files and folders.",
  },
  {
    repository: "biomejs/biome",
    url: "https://github.com/biomejs/biome",
    stars: 25578,
    mergedPullRequests: 1,
    description:
      "A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI and LSP.",
  },
  {
    repository: "spicetify/cli",
    url: "https://github.com/spicetify/cli",
    stars: 24073,
    mergedPullRequests: 36,
    description:
      "Command-line tool to customize Spotify client. Supports Windows, macOS, and Linux.",
  },
  {
    repository: "Homebrew/homebrew-cask",
    url: "https://github.com/Homebrew/homebrew-cask",
    stars: 22167,
    mergedPullRequests: 3,
    description:
      "🍻 Default casks (upstream binary packages) for the package manager for everywhere",
  },
  {
    repository: "decaporg/decap-cms",
    url: "https://github.com/decaporg/decap-cms",
    stars: 19295,
    mergedPullRequests: 1,
    description: "A Git-based CMS for Static Site Generators",
  },
  {
    repository: "diegomura/react-pdf",
    url: "https://github.com/diegomura/react-pdf",
    stars: 16746,
    mergedPullRequests: 1,
    description: "📄  Create PDF files using React",
  },
  {
    repository: "electron-userland/electron-builder",
    url: "https://github.com/electron-userland/electron-builder",
    stars: 14641,
    mergedPullRequests: 1,
    description:
      "A complete solution to package and build a ready for distribution Electron app with “auto update” support out of the box",
  },
  {
    repository: "reactjs/react.dev",
    url: "https://github.com/reactjs/react.dev",
    stars: 11785,
    mergedPullRequests: 1,
    description: "The React documentation website",
  },
  {
    repository: "emdash-cms/emdash",
    url: "https://github.com/emdash-cms/emdash",
    stars: 11621,
    mergedPullRequests: 1,
    description:
      "EmDash is a full-stack TypeScript CMS based on Astro; the spiritual successor to WordPress",
  },
  {
    repository: "raineorshine/npm-check-updates",
    url: "https://github.com/raineorshine/npm-check-updates",
    stars: 10298,
    mergedPullRequests: 1,
    description: "Find newer versions of package dependencies than what your package.json allows",
  },
  {
    repository: "t3-oss/create-t3-turbo",
    url: "https://github.com/t3-oss/create-t3-turbo",
    stars: 6097,
    mergedPullRequests: 1,
    description: "Clean and simple starter repo using the T3 Stack along with Expo React Native",
  },
  {
    repository: "spicetify/spicetify-themes",
    url: "https://github.com/spicetify/spicetify-themes",
    stars: 6041,
    mergedPullRequests: 7,
    description:
      "A community-driven collection of themes for customizing Spotify through Spicetify - https://github.com/spicetify/cli",
  },
  {
    repository: "solidjs/solid-start",
    url: "https://github.com/solidjs/solid-start",
    stars: 5906,
    mergedPullRequests: 1,
    description: "SolidStart, the Solid app framework",
  },
  {
    repository: "jef/streetmerchant",
    url: "https://github.com/jef/streetmerchant",
    stars: 5401,
    mergedPullRequests: 2,
    description: "🤖 The world's easiest, most powerful stock checker",
  },
  {
    repository: "gitify-app/gitify",
    url: "https://github.com/gitify-app/gitify",
    stars: 5317,
    mergedPullRequests: 140,
    description: "Git notifications on your menu bar. Available on macOS, Windows & Linux.",
  },
  {
    repository: "dubzzz/fast-check",
    url: "https://github.com/dubzzz/fast-check",
    stars: 5098,
    mergedPullRequests: 1,
    description:
      "Property based testing framework for JavaScript (like QuickCheck) written in TypeScript",
  },
  {
    repository: "homarr-labs/homarr",
    url: "https://github.com/homarr-labs/homarr",
    stars: 4536,
    mergedPullRequests: 9,
    description:
      "A modern and easy to use dashboard. 40+ integrations. 20K+ icons built in. Authentication out of the box. No YAML, drag and drop configuration.",
  },
  {
    repository: "nubjs/nub",
    url: "https://github.com/nubjs/nub",
    stars: 3982,
    mergedPullRequests: 4,
    description: "The fast all-in-one Node.js toolkit",
  },
  {
    repository: "mozilla/web-ext",
    url: "https://github.com/mozilla/web-ext",
    stars: 3126,
    mergedPullRequests: 1,
    description: "A command line tool to help build, run, and test web extensions",
  },
  {
    repository: "jpudysz/react-native-unistyles",
    url: "https://github.com/jpudysz/react-native-unistyles",
    stars: 2934,
    mergedPullRequests: 1,
    description: "Level up your React Native StyleSheet",
  },
  {
    repository: "withastro/docs",
    url: "https://github.com/withastro/docs",
    stars: 1678,
    mergedPullRequests: 2,
    description: "Astro documentation",
  },
  {
    repository: "spicetify/marketplace",
    url: "https://github.com/spicetify/marketplace",
    stars: 1535,
    mergedPullRequests: 4,
    description: "Download extensions and themes directly from Spicetify",
  },
  {
    repository: "marmelo/tech-companies-in-portugal",
    url: "https://github.com/marmelo/tech-companies-in-portugal",
    stars: 1515,
    mergedPullRequests: 57,
    description: ":portugal: List of technology companies in Portugal.",
  },
  {
    repository: "hoodie/notify-rust",
    url: "https://github.com/hoodie/notify-rust",
    stars: 1417,
    mergedPullRequests: 1,
    description: "☝️send desktop notifications from your Rust app.",
  },
  {
    repository: "typescript-eslint/tslint-to-eslint-config",
    url: "https://github.com/typescript-eslint/tslint-to-eslint-config",
    stars: 861,
    mergedPullRequests: 1,
    description: "Converts your TSLint configuration to the closest possible ESLint equivalent. 🚀",
  },
  {
    repository: "apisyouwonthate/openapi.tools",
    url: "https://github.com/apisyouwonthate/openapi.tools",
    stars: 841,
    mergedPullRequests: 1,
    description:
      "The most comprehensive collection of quality OpenAPI tooling, curated by Phil Sturgeon and the team at APIs You Won't Hate.",
  },
  {
    repository: "Comfy-Themes/Spicetify",
    url: "https://github.com/Comfy-Themes/Spicetify",
    stars: 796,
    mergedPullRequests: 3,
    description: "Stay comfy while listening to music",
  },
  {
    repository: "oven-sh/setup-bun",
    url: "https://github.com/oven-sh/setup-bun",
    stars: 714,
    mergedPullRequests: 1,
    description: "Set up your GitHub Actions workflow with a specific version of Bun",
  },
  {
    repository: "vicrodh/qbz",
    url: "https://github.com/vicrodh/qbz",
    stars: 629,
    mergedPullRequests: 48,
    description:
      "A native, full-featured hi-fi Qobuz desktop player for Linux and MacOS, with fast, bit-perfect audio playback.",
  },
  {
    repository: "acro5piano/react-native-big-calendar",
    url: "https://github.com/acro5piano/react-native-big-calendar",
    stars: 588,
    mergedPullRequests: 5,
    description: "gcal/outlook like calendar component for React Native",
  },
  {
    repository: "auth0/react-native-auth0",
    url: "https://github.com/auth0/react-native-auth0",
    stars: 552,
    mergedPullRequests: 1,
    description: "React Native toolkit for Auth0 API",
  },
  {
    repository: "mercuretechnologies/xprem",
    url: "https://github.com/mercuretechnologies/xprem",
    stars: 485,
    mergedPullRequests: 3,
    description:
      "Self-hosted Expo OTA Updates alternative to EAS Update, on the official Expo Updates protocol. Multi-app dashboard, progressive rollouts, instant rollbacks, and per-update crashes, metrics and logs from every device via expo-observe. Your bucket, your CDN, your data. Formerly expo-open-ota.",
  },
  {
    repository: "Richienb/node-polyfill-webpack-plugin",
    url: "https://github.com/Richienb/node-polyfill-webpack-plugin",
    stars: 302,
    mergedPullRequests: 2,
    description: "Polyfill Node.js core modules in Webpack.",
  },
  {
    repository: "RustAudio/coreaudio-rs",
    url: "https://github.com/RustAudio/coreaudio-rs",
    stars: 295,
    mergedPullRequests: 1,
    description: "A friendly rust interface to Apple's Core Audio API.",
  },
  {
    repository: "Azure/openapi-diff",
    url: "https://github.com/Azure/openapi-diff",
    stars: 289,
    mergedPullRequests: 2,
    description: "Command line tool to detect breaking changes between two openapi specifications",
  },
  {
    repository: "spicetify/docs",
    url: "https://github.com/spicetify/docs",
    stars: 193,
    mergedPullRequests: 48,
    description: "Documentation website for spicetify",
  },
  {
    repository: "solidjs/solid-docs-legacy",
    url: "https://github.com/solidjs/solid-docs-legacy",
    stars: 190,
    mergedPullRequests: 1,
    description:
      "OLD documentation for SolidJS and related packages, replaced by https://github.com/solidjs/solid-docs-next",
  },
  {
    repository: "Typescript-TDD/jest-ts-auto-mock",
    url: "https://github.com/Typescript-TDD/jest-ts-auto-mock",
    stars: 169,
    mergedPullRequests: 1,
    description: "Jest test utility with automatic mock creation for interfaces and classes",
  },
  {
    repository: "aquelemiguel/parrot",
    url: "https://github.com/aquelemiguel/parrot",
    stars: 155,
    mergedPullRequests: 58,
    description:
      "🦜 A hassle-free, highly performant, self-hosted Discord music bot with YouTube and Spotify support. Powered by yt-dlp.",
  },
  {
    repository: "refstudio/refstudio",
    url: "https://github.com/refstudio/refstudio",
    stars: 68,
    mergedPullRequests: 1,
    description:
      "Ref Studio is an open source integrated writing environment for technical writing",
  },
  {
    repository: "yldio/whisper-ui",
    url: "https://github.com/yldio/whisper-ui",
    stars: 7,
    mergedPullRequests: 11,
    description: "Helper native app to run whisper on local machines.",
  },
  {
    repository: "msramalho/feup-lbaw",
    url: "https://github.com/msramalho/feup-lbaw",
    stars: 6,
    mergedPullRequests: 6,
    description:
      "University Subject - Monstrous project done with Laravel and some of its features",
  },
  {
    repository: "gitify-app/electron-menubar",
    url: "https://github.com/gitify-app/electron-menubar",
    stars: 3,
    mergedPullRequests: 48,
    description: "➖ High level way to create menubar desktop applications with Electron",
  },
  {
    repository: "spicetify/modules",
    url: "https://github.com/spicetify/modules",
    stars: 3,
    mergedPullRequests: 1,
    description: "The vault for official modules for spicetify v3",
  },
  {
    repository: "spicetify/classmaps",
    url: "https://github.com/spicetify/classmaps",
    stars: 1,
    mergedPullRequests: 2,
  },
  {
    repository: "gitify-app/website",
    url: "https://github.com/gitify-app/website",
    stars: 0,
    mergedPullRequests: 9,
    description: "The source code of gitify.io",
  },
];
