import type { Year } from "~/types/content";

export const music: Year[] = [
  {
    year: "2025",
    concerts: [
      {
        title: "Capicua",
        location: "Casa da Música",
        image: "/music/capicua.webp",
      },
      {
        title: "Clarissa Connelly",
        location: "Tremor",
        image: "/music/clarissa-connelly.webp",
      },
    ],
    albums: [
      {
        title: "Virgin",
        artist: "Lorde",
        image: "/music/virgin.webp",
        url: "https://open.spotify.com/album/28bHj2enHkHVFLwuWmkwlQ",
      },
      {
        title: "Dog Eared",
        artist: "Billie Marten",
        image: "/music/dog-eared.webp",
        url: "https://open.spotify.com/album/79zQn0JeZ9tVX2T0VvpDGi",
      },
      {
        title: "hopefully !",
        artist: "Loyle Carner",
        image: "/music/hopefully.webp",
        url: "https://open.spotify.com/album/3QiiMhk65fgCPOKThjZ8iK",
      },
      {
        title: "Lotus",
        artist: "Little Simz",
        image: "/music/lotus.webp",
        url: "https://open.spotify.com/album/0ofdTvYtx4LpsVjemJt71X",
      },
      {
        title: "MARAVILHOSAMENTE BEM",
        artist: "Julia Mestre",
        image: "/music/maravilhosamente-bem.webp",
        url: "https://open.spotify.com/album/6hKQF3IhyBlr6LE5K2nkYY",
      },
      {
        title: "NEVER ENOUGH",
        artist: "Turnstile",
        image: "/music/never-enough.webp",
        url: "https://open.spotify.com/album/52yD51X7yDinwlg6tbCtpP",
      },
      {
        title: "EUSEXUA",
        artist: "FKA twigs",
        image: "/music/eusexua.webp",
        url: "https://open.spotify.com/album/3o1TOhMkU5FFMSJMDhXfdF",
      },
    ],
  },
  {
    year: "2024",
    concerts: [
      {
        title: "MASS OF THE FERMENTING DREGS",
        location: "Hard Club",
        image: "/music/mass-of-the-fermenting-dregs.webp",
      },
      {
        title: "Patrick Watson",
        location: "Hard Club",
        image: "/music/patrick-watson.webp",
      },
      {
        title: "Blowfuse",
        location: "Woodstock 69",
        image: "/music/blowfuse.webp",
      },
      {
        title: "Sereias",
        location: "FAUP Fest",
        image: "/music/sereias.webp",
      },
      {
        title: "The Last Dinner Party",
        location: "Primavera Sound",
        image: "/music/the-last-dinner-party.webp",
      },
    ],
    albums: [
      {
        title: "She Reaches Out To She Reaches Out To She",
        artist: "Chelsea Wolfe",
        image: "/music/she-reaches-out-to-she-reaches-out-to-she.webp",
        url: "https://open.spotify.com/album/4uJMF1xAEk9IgPA5UbwNA6",
      },
      {
        title: "Prelude to Ecstasy",
        artist: "The Last Dinner Party",
        image: "/music/prelude-to-ecstasy.webp",
        url: "https://open.spotify.com/album/1ycq58KRtWt3wFtbuIkvLn",
      },
      {
        title: "World of Work",
        artist: "Clarissa Connelly",
        image: "/music/world-of-work.webp",
        url: "https://open.spotify.com/album/7r1cQPyAwQfhQIw9H9eGB5",
      },
      {
        title: "TANGK",
        artist: "IDLES",
        image: "/music/tangk.webp",
        url: "https://open.spotify.com/album/6U11VNHZAfYY3E9V4oFB2p",
      },
      {
        title: "The New Sound",
        artist: "Geordie Greep",
        image: "/music/the-new-sound.webp",
        url: "https://open.spotify.com/album/07YS7ooqYtvPZLlW59MHY5",
      },
      {
        title: "“NO TITLE AS OF 13 FEBRUARY 2024 28,340 DEAD”",
        artist: "Godspeed You! Black Emperor",
        image: "/music/no-title-as-of-13-february-2024-28-340-dead.webp",
        url: "https://open.spotify.com/album/1qG30zCAZ30hsmA5wAlaQ3",
      },
      {
        title: "Imaginal Disk",
        artist: "Magdalena Bay",
        image: "/music/imaginal-disk.webp",
        url: "https://open.spotify.com/album/4HTy9WFTYooRjE9giTmzAF",
      },
      {
        title: "Samurai",
        artist: "Lupe Fiasco",
        image: "/music/samurai.webp",
        url: "https://open.spotify.com/album/1O6d4cNuUV78GeXv7hgr4e",
      },
      {
        title: "Enciclopédia",
        artist: "Pangema",
        image: "/music/enciclopedia.webp",
        url: "https://open.spotify.com/album/3WsfjEXj9TN4aTuX0yCqsN",
      },
      {
        title: "BRAT",
        artist: "Charli xcx",
        image: "/music/brat.webp",
        url: "https://open.spotify.com/album/2lIZef4lzdvZkiiCzvPKj7",
      },
      {
        title: "Glimmer of God",
        artist: "Jean Dawson",
        image: "/music/glimmer-of-god.webp",
        url: "https://open.spotify.com/album/2sdEcm60h3HBZkd5k7SkRh",
      },
    ],
  },
  {
    year: "2023",
    concerts: [
      {
        title: "Billy Woods",
        location: "Galeria Zé dos Bois",
        image: "/music/billy-woods.webp",
      },
      {
        title: "José Cid",
        location: "Casa da Música",
        image: "/music/jose-cid.webp",
      },
      {
        title: "Fred Again..",
        location: "Primavera Sound",
        image: "/music/fred-again.webp",
      },
      {
        title: "Jockstrap",
        location: "Primavera Sound",
        image: "/music/jockstrap.webp",
      },
      {
        title: "MÁQUINA.",
        location: "concertos que nunca existiram",
        image: "/music/maquina.webp",
      },
      {
        title: "Weyes Blood",
        location: "Hard Club",
        image: "/music/weyes-blood.webp",
      },
      {
        title: "Despirited Spirits",
        location: "Maus Hábitos",
        image: "/music/despirited-spirits.webp",
      },
    ],
    albums: [
      {
        title: "Me Chama De Gato Que Eu Sou Sua",
        artist: "Ana Frango Elétrico",
        image: "/music/me-chama-de-gato-que-eu-sou-sua.webp",
        url: "https://open.spotify.com/album/6UZpK4jB5MYVYJpwwi2mbP",
      },
      {
        title: "DIRTY TRACKS FOR CLUBBING",
        artist: "MAQUINA.",
        image: "/music/dirty-tracks-for-clubbing.webp",
        url: "https://open.spotify.com/album/7vCLEizWTP0lqwuG3GHihu",
      },
      {
        title: "Afro Fado",
        artist: "Slow J",
        image: "/music/afro-fado.webp",
        url: "https://open.spotify.com/album/0GcsYtidlr4azVnuTjD3KI",
      },
      {
        title: "The Land Is Inhospitable and So Are We",
        artist: "Mitski",
        image: "/music/the-land-is-inhospitable-and-so-are-we.webp",
        url: "https://open.spotify.com/album/2Cn1d2KgbkAqbZCJ1RzdkA",
      },
      {
        title: "Javelin",
        artist: "Sufjan Stevens",
        image: "/music/javelin.webp",
        url: "https://open.spotify.com/album/2KqSL3vLfyVO7rrZJL9tUs",
      },
      {
        title: "Desire, I Want To Turn Into You",
        artist: "Caroline Polachek",
        image: "/music/desire-i-want-to-turn-into-you.webp",
        url: "https://open.spotify.com/album/22PkV1Le9P3X4RY4xtmK0q",
      },
      {
        title: "The Redshift Blues",
        artist: "Dispirited Spirits",
        image: "/music/the-redshift-blues.webp",
        url: "https://open.spotify.com/album/5X0zmtiglsalNjS6uJj6iI",
      },
      {
        title: "Let’s Start Here.",
        artist: "Lil Yachty",
        image: "/music/let-s-start-here.webp",
        url: "https://open.spotify.com/album/6Per97deaWqrJlKQNX8RGK",
      },
      {
        title: "Wait Til I Get Over",
        artist: "Durand Jones",
        image: "/music/wait-til-i-get-over.webp",
        url: "https://open.spotify.com/album/3t5PKVYlbYXIiLIRDPPkp4",
      },
      {
        title: "Space Heavy",
        artist: "King Krule",
        image: "/music/space-heavy.webp",
        url: "https://open.spotify.com/album/36tUlc8fGxaUTv4cLmC9UJ",
      },
      {
        title: "Lucifer Pool Party",
        artist: "Lucifer Pool Party",
        image: "/music/lucifer-pool-party.webp",
        url: "https://open.spotify.com/album/6nZ5GLdXcXIE2yyFgkgLCG",
      },
      {
        title: "Dogsbody",
        artist: "Model/Actriz",
        image: "/music/dogsbody.webp",
        url: "https://open.spotify.com/album/1DWLFwBZxTSBWw7G9uhpok",
      },
      {
        title: "Knocknarea",
        artist: "Maruja",
        image: "/music/knocknarea.webp",
        url: "https://open.spotify.com/album/1hb0fuPRhbd1uStttAaalz",
      },
    ],
  },
  {
    year: "2022",
    concerts: [
      {
        title: "Extrazen",
        location: "Plano B - Porto",
        image: "/music/extrazen.webp",
      },
      {
        title: "L'Imperatrice",
        location: "Paredes de Coura",
        image: "/music/l-imperatrice.webp",
      },
      {
        title: "IDLES",
        location: "Paredes de Coura",
        image: "/music/idles.webp",
      },
      {
        title: "Bad Bad Not Good - MF Doom Tribute",
        location: "Paredes de Coura",
        image: "/music/bad-bad-not-good-mf-doom-tribute.webp",
      },
      {
        title: "Floating Points",
        location: "Apollo - Barcelona",
        image: "/music/floating-points.webp",
      },
      {
        title: "Little Simz",
        location: "Primavera Sound Porto",
        image: "/music/little-simz.webp",
      },
      {
        title: "Squid",
        location: "Primavera Sound Porto",
        image: "/music/squid.webp",
      },
      {
        title: "Caroline Polachek",
        location: "Primavera Sound Porto",
        image: "/music/caroline-polachek.webp",
      },
      {
        title: "Black Midi",
        location: "Primavera Sound Porto",
        image: "/music/black-midi.webp",
      },
      {
        title: "Bala Desejo",
        location: "Hotel Mouco",
        image: "/music/bala-desejo.webp",
      },
    ],
    albums: [
      {
        title: "I Love You Jennifer B",
        artist: "Jockstrap",
        image: "/music/i-love-you-jennifer-b.webp",
        url: "https://open.spotify.com/album/4YFlC5Abaj48ERwaOPfpu8",
      },
      {
        title: "Ants From Up There",
        artist: "Black Country, New Road",
        image: "/music/ants-from-up-there.webp",
        url: "https://open.spotify.com/album/21xp7NdU1ajmO1CX0w2Egd",
      },
      {
        title: "CRASH",
        artist: "Charli XCX",
        image: "/music/crash.webp",
        url: "https://open.spotify.com/album/1QqipMXWzJhr6yfcNKTp8B",
      },
      {
        title: "And In The Darkness, Hearts Aglow",
        artist: "Weyes Blood",
        image: "/music/and-in-the-darkness-hearts-aglow.webp",
        url: "https://open.spotify.com/album/1hngVRZt95TrqPqXoJzQ4A",
      },
      {
        title: "You Belong There",
        artist: "Daniel Rossen",
        image: "/music/you-belong-there.webp",
        url: "https://open.spotify.com/album/1eb8tDRzXuhb3omC50SkHt",
      },
      {
        title: "Actual Life 3 (January 1 - September 9 2022)",
        artist: "Fred again..",
        image: "/music/actual-life-3-january-1-september-9-2022.webp",
        url: "https://open.spotify.com/album/5q2iMctlDvEMYVIawF6Vop",
      },
      {
        title: "Dragon New Warm Mountain I Believe In You",
        artist: "Big Thief",
        image: "/music/dragon-new-warm-mountain-i-believe-in-you.webp",
        url: "https://open.spotify.com/album/7Ln81p86r5cCsesd3KBWIY",
      },
      {
        title: "Melt My Eyez See Your Future (The Extended Edition)",
        artist: "Denzel Curry",
        image: "/music/melt-my-eyez-see-your-future-the-extended-edition.webp",
        url: "https://open.spotify.com/album/5eXL40WFKPjdCw0NZrRcJI",
      },
      {
        title: "De Todas las Flores",
        artist: "Natalia Lafourcade",
        image: "/music/de-todas-las-flores.webp",
        url: "https://open.spotify.com/album/4BJoDX0fIjR4RsFF4vyd81",
      },
      {
        title: "Aethiopes",
        artist: "billy woods",
        image: "/music/aethiopes.webp",
        url: "https://open.spotify.com/album/34uTUAM6SE8Eo6Cv4PRqwD",
      },
      {
        title: "NO THANK YOU",
        artist: "Little Simz",
        image: "/music/no-thank-you.webp",
        url: "https://open.spotify.com/album/57263zG8Md6XZ9lBUPPYCm",
      },
      {
        title: "MOTOMAMI",
        artist: "ROSALÍA",
        image: "/music/motomami.webp",
        url: "https://open.spotify.com/album/6jbtHi5R0jMXoliU2OS0lo",
      },
      {
        title: "Ice, Death, Planets, Lungs, Mushrooms And Lava",
        artist: "King Gizzard & The Lizard Wizard",
        image: "/music/ice-death-planets-lungs-mushrooms-and-lava.webp",
        url: "https://open.spotify.com/album/2nPbslvl01lfELsFHTKp0s",
      },
      {
        title: "SIM SIM SIM",
        artist: "Bala Desejo",
        image: "/music/sim-sim-sim.webp",
        url: "https://open.spotify.com/album/5lPgAWFWtQOUllSFzoWJtx",
      },
      {
        title: "Florist",
        artist: "Florist",
        image: "/music/florist.webp",
        url: "https://open.spotify.com/album/7EvfFPMMvMJ20olfdEkPBR",
      },
      {
        title: "Mil Coisas Invisíveis",
        artist: "Tim Bernardes",
        image: "/music/mil-coisas-invisiveis.webp",
        url: "https://open.spotify.com/album/1I74KuYarc1dMEgZ0io50Y",
      },
      {
        title: "Death Is a Dream",
        artist: "HTRK",
        image: "/music/death-is-a-dream.webp",
        url: "https://open.spotify.com/album/3yOjzY8Hj1JPKBCWoB3gvI",
      },
      {
        title: "Hyper-Dimensional Expansion Beam",
        artist: "The Comet Is Coming",
        image: "/music/hyper-dimensional-expansion-beam.webp",
        url: "https://open.spotify.com/album/1XPsJnIVMjOt04rczMWVO4",
      },
      {
        title: "Hellfire",
        artist: "black midi",
        image: "/music/hellfire.webp",
        url: "https://open.spotify.com/album/68z6MWYYNmvTcru1QMcYId",
      },
      {
        title: "$oul $old $eparately",
        artist: "Freddie Gibbs",
        image: "/music/oul-old-eparately.webp",
        url: "https://open.spotify.com/album/3PZx4Vntcp5T7UgdfjnFDa",
      },
      {
        title: "hugo",
        artist: "Loyle Carner",
        image: "/music/hugo.webp",
        url: "https://open.spotify.com/album/3McfY0EGNjsrVdYa9ZnoSH",
      },
    ],
  },
  {
    year: "2021",
    concerts: [
      {
        title: "Sensible Soccers",
        location: "Manoel Debut - Serralves",
        image: "/music/sensible-soccers.webp",
      },
      {
        title: "Raquel Martins",
        location: "Hot Five Uptown - Porto",
        image: "/music/raquel-martins.webp",
      },
    ],
    albums: [
      {
        title: "For the first time",
        artist: "Black Country, New Road",
        image: "/music/for-the-first-time.webp",
        url: "https://open.spotify.com/album/2PfgptDcfJTFtoZIS3AukX",
      },
      {
        title: "Sweet Talk",
        artist: "Spellling",
        image: "/music/sweet-talk.webp",
        url: "https://open.spotify.com/track/6FqORNXMSWhXbWIZGioC9t",
      },
      {
        title: "Promises",
        artist: "Floating Points",
        image: "/music/promises.webp",
        url: "https://open.spotify.com/album/3ShtO5VCYa3ctlR5uzLWBa",
      },
      {
        title: "Cavalcade",
        artist: "black midi",
        image: "/music/cavalcade.webp",
        url: "https://open.spotify.com/album/7AsC27VDa3yOksZrfBSD6D",
      },
      {
        title: "Bright Green Field",
        artist: "Squid",
        image: "/music/bright-green-field.webp",
        url: "https://open.spotify.com/album/4z44Wir05QzQYSCs0KwsKX",
      },
      {
        title: "Jubilee",
        artist: "Japanese Breakfast",
        image: "/music/jubilee.webp",
        url: "https://open.spotify.com/album/0ajoNtBO6xHfWEkORtRCAv",
      },
      {
        title: "To See the Next Part of the Dream",
        artist: "파란노을 [Parannoul]",
        image: "/music/to-see-the-next-part-of-the-dream.webp",
        url: "https://open.spotify.com/album/0sLt9EsWnVZgJAO5Sp35YQ",
      },
      {
        title: "Fragments of a Dying Star",
        artist: "Dispirited Spirits",
        image: "/music/fragments-of-a-dying-star.webp",
        url: "https://open.spotify.com/album/6rGRUCqGLJ0KHHm6O1lk7M",
      },
      {
        title: "Collapsed In Sunbeams",
        artist: "Arlo Parks",
        image: "/music/collapsed-in-sunbeams.webp",
        url: "https://open.spotify.com/album/42joEEymK7EIHODfNB4yug",
      },
      {
        title: "Drunk Tank Pink",
        artist: "shame",
        image: "/music/drunk-tank-pink.webp",
        url: "https://open.spotify.com/album/7hl54HF6Nykh5IDrbqhiJX",
      },
      {
        title: "Te Amo Lá Fora",
        artist: "DUDA BEAT",
        image: "/music/te-amo-la-fora.webp",
        url: "https://open.spotify.com/album/5o6MJpi6Y4fQwI8gmv0oZc",
      },
      {
        title: "Manoel",
        artist: "Sensible Soccers",
        image: "/music/manoel.webp",
        url: "https://open.spotify.com/album/543Od6jPztHDBppscYO0J6",
      },
      {
        title: "Mood Valiant",
        artist: "Hiatus Kaiyote",
        image: "/music/mood-valiant.webp",
        url: "https://open.spotify.com/album/456WeVeZk38VJuqg2sL7QG",
      },
      {
        title: "Peace Or Love",
        artist: "Kings of Convenience",
        image: "/music/peace-or-love.webp",
        url: "https://open.spotify.com/album/1I8t93pjEtNM1vbtoUII0m",
      },
      {
        title: "Sometimes I Might Be Introvert",
        artist: "Little Simz",
        image: "/music/sometimes-i-might-be-introvert.webp",
        url: "https://open.spotify.com/album/0DBoWQ52XUHtrZQdfAqOVj",
      },
      {
        title: "CALL ME IF YOU GET LOST",
        artist: "Tyler, The Creator",
        image: "/music/call-me-if-you-get-lost.webp",
        url: "https://open.spotify.com/album/45ba6QAtNrdv6Ke4MFOKk9",
      },
      {
        title: "CRAWLER",
        artist: "IDLES",
        image: "/music/crawler.webp",
        url: "https://open.spotify.com/album/27ygqCfb4dXQ3jyXnC58FU",
      },
      {
        title: "SINNER GET READY",
        artist: "Lingua Ignota",
        image: "/music/sinner-get-ready.webp",
        url: "https://open.spotify.com/album/06wtf2TCkmyTgS1yZGiSr5",
      },
      {
        title: "Daddy's Home",
        artist: "St. Vincent",
        image: "/music/daddy-s-home.webp",
        url: "https://open.spotify.com/album/654KFpNOZ26Hj9luu7aKeM",
      },
      {
        title: "Once Twice Melody",
        artist: "Beach House",
        image: "/music/once-twice-melody.webp",
        url: "https://open.spotify.com/album/4TXjlsgAAdeiIZl63oMpW4",
      },
      {
        title: "KicK iii",
        artist: "Arca",
        image: "/music/kick-iii.webp",
        url: "https://open.spotify.com/album/1paea7BPqUpZksvNkQ2cqQ",
      },
    ],
  },
  {
    year: "2020",
    concerts: [
      {
        title: "Salvador e Luísa Sobral",
        location: "Teatro Sá da Bandeira - Porto",
        image: "/music/salvador-e-luisa-sobral.webp",
      },
      {
        title: "Manel Cruz",
        location: "Teatro Sá da Bandeira - Porto",
        image: "/music/manel-cruz.webp",
      },
      {
        title: "André Henriques",
        location: "Teatro Cinema - Fafe",
        image: "/music/andre-henriques.webp",
      },
      {
        title: "Fugly",
        location: "Concertos de Bolso (Feira do Livro) - Porto",
        image: "/music/fugly.webp",
      },
    ],
    albums: [
      {
        title: "Alfredo",
        artist: "Freddie Gibbs & The Alchemist",
        image: "/music/alfredo.webp",
        url: "https://open.spotify.com/album/3znl1qe13kyjQv7KcR685N?si=2SswTE2jSLC7x6keFJhwuQ&dl_branch=1",
      },
      {
        title: "Punisher",
        artist: "Phoebe Bridgers",
        image: "/music/punisher.webp",
        url: "https://open.spotify.com/album/2xECuqnvvmVktV7UO8Dd3s",
      },
      {
        title: "The New Abnormal",
        artist: "The Strokes",
        image: "/music/the-new-abnormal.webp",
        url: "https://open.spotify.com/album/2xkZV2Hl1Omi8rk2D7t5lN",
      },
      {
        title: "アダンの風 (Windswept Adan)",
        artist: "Ichiko Aoba",
        image: "/music/windswept-adan.webp",
        url: "https://open.spotify.com/album/1W0SccGphtGQNYqaqQ5nhA",
      },
      {
        title: "Circles",
        artist: "Mac Miller",
        image: "/music/circles.webp",
        url: "https://open.spotify.com/album/5sY6UIQ32GqwMLAfSNEaXb",
      },
      {
        title: "Shore",
        artist: "Fleet Foxes",
        image: "/music/shore.webp",
        url: "https://open.spotify.com/album/0lmjCPEcec2k6L7ysNIcd3",
      },
      {
        title: "Future Nostalgia",
        artist: "Dua Lipa",
        image: "/music/future-nostalgia.webp",
        url: "https://open.spotify.com/album/7fJJK56U9fHixgO0HQkhtI",
      },
      {
        title: "songs",
        artist: "Adrianne Lenker",
        image: "/music/songs.webp",
        url: "https://open.spotify.com/album/2WKfCjW3EDmgHswj5eVXuG",
      },
      {
        title: "Shabrang",
        artist: "Sevdaliza",
        image: "/music/shabrang.webp",
        url: "https://open.spotify.com/album/54tTC9UQtLnu5Wldhlnstr",
      },
      {
        title: "Dinner Party",
        artist: "Terrace Martin",
        image: "/music/dinner-party.webp",
        url: "https://open.spotify.com/album/4Wq9dC08uEtSuGc8mFwC3r",
      },
      {
        title: "Set My Heart On Fire Immediately",
        artist: "Perfume Genius",
        image: "/music/set-my-heart-on-fire-immediately.webp",
        url: "https://open.spotify.com/album/5qWrp5RcqjxB8ak7dtK6Iv",
      },
      {
        title: "how i'm feeling now",
        artist: "Charli XCX",
        image: "/music/how-i-m-feeling-now.webp",
        url: "https://open.spotify.com/album/3a9qH2VEsSiOZvMrjaS0Nu",
      },
      {
        title: "2017 - 2019",
        artist: "Against All Logic",
        image: "/music/2017-2019.webp",
        url: "https://open.spotify.com/album/75vFTgDgdfVhbniLoyCNKh",
      },
      {
        title: "Cajarana",
        artist: "André Henriques",
        image: "/music/cajarana.webp",
        url: "https://open.spotify.com/album/1d2VTPkIvTzRa9hnAwHpcC",
      },
    ],
  },
  {
    year: "2019",
    description: "This was an amazing year for music 🥰",
    concerts: [
      {
        title: "King Gizzard and the Lizzard Wizzard",
        location: "Razzmatazz - Barcelona",
        image: "/music/king-gizzard-and-the-lizzard-wizzard.webp",
      },
      {
        title: "The National",
        location: "Paredes de Coura",
        image: "/music/the-national.webp",
      },
    ],
    albums: [
      {
        title: "Titanic Rising",
        artist: "Weyes Blood",
        image: "/music/titanic-rising.webp",
        url: "https://open.spotify.com/album/53VKICyqCf91sVkTdFrzKX",
      },
      {
        title: "KIWANUKA",
        artist: "Michael Kiwanuka",
        image: "/music/kiwanuka.webp",
        url: "https://open.spotify.com/album/1yIqauTni1V7l7djYAKSsZ",
      },
      {
        title: "MAGDALENE",
        artist: "FKA twigs",
        image: "/music/magdalene.webp",
        url: "https://open.spotify.com/album/2w8Wshbp9RCPJdPU1iOpaY",
      },
      {
        title: "IGOR",
        artist: "Tyler, The Creator",
        image: "/music/igor.webp",
        url: "https://open.spotify.com/album/5zi7WsKlIiUXv09tbGLKsE",
      },
      {
        title: "Infest The Rats' Nest",
        artist: "King Gizzard & The Lizard Wizard",
        image: "/music/infest-the-rats-nest.webp",
        url: "https://open.spotify.com/album/5Bz2LxOp0wz7ov0T9WiRmc",
      },
      {
        title: "GREY Area",
        artist: "Little Simz",
        image: "/music/grey-area.webp",
        url: "https://open.spotify.com/album/4Wwm4xg2748zhYuzDRFTgY",
      },
      {
        title: "Bandana",
        artist: "Freddie Gibbs, Madlib",
        image: "/music/bandana.webp",
        url: "https://open.spotify.com/album/31KbO7WnDp2AjPdmRTJzdf",
      },
      {
        title: "Pang",
        artist: "Caroline Polachek",
        image: "/music/pang.webp",
        url: "https://open.spotify.com/album/4ClyeVlAKJJViIyfVW0yQD",
      },
      {
        title: "ANIMA",
        artist: "Thom Yorke",
        image: "/music/anima.webp",
        url: "https://open.spotify.com/album/1g4vEVvVVFvFju0gS0DMbh",
      },
      {
        title: "Designer",
        artist: "Aldous Harding",
        image: "/music/designer.webp",
        url: "https://open.spotify.com/album/0QNJa03XQeMOuQhi9izThh",
      },
      {
        title: "Ventura",
        artist: "Anderson .Paak",
        image: "/music/ventura.webp",
        url: "https://open.spotify.com/album/0YF8PfcGbsKg5IaFyPnlyY",
      },
      {
        title: "Injury Reserve",
        artist: "Injury Reserve",
        image: "/music/injury-reserve.webp",
        url: "https://open.spotify.com/album/5UWKsRDw3O4BsobmeyRpB9",
      },
      {
        title: "Assume Form",
        artist: "James Blake",
        image: "/music/assume-form.webp",
        url: "https://open.spotify.com/album/1LJE8ppunlaafUQzNJsxl2",
      },
      {
        title: "My Finest Work Yet",
        artist: "Andrew Bird",
        image: "/music/my-finest-work-yet.webp",
        url: "https://open.spotify.com/album/2xQ1WHVV0MdVSRkpND5P51",
      },
      {
        title: "Wave",
        artist: "Patrick Watson",
        image: "/music/wave.webp",
        url: "https://open.spotify.com/album/4sgJYX3we1RoranerDs8ph",
      },
      {
        title: "American Love Call",
        artist: "Durand Jones & The Indications",
        image: "/music/american-love-call.webp",
        url: "https://open.spotify.com/album/7FU0CDJvPwKDWRXtHYcsoY",
      },
      {
        title: "GINGER",
        artist: "BROCKHAMPTON",
        image: "/music/ginger.webp",
        url: "https://open.spotify.com/album/1jToVugwBEzcak8gJNZG2f",
      },
      {
        title: "ARIZONA BABY",
        artist: "Kevin Abstract",
        image: "/music/arizona-baby.webp",
        url: "https://open.spotify.com/album/6wi40lIjhukePWyXRKY7qO",
      },
      {
        title: "Miami Memory",
        artist: "Alex Cameron",
        image: "/music/miami-memory.webp",
        url: "https://open.spotify.com/album/33u2PRETjYklC6UqxJBGW2",
      },
      {
        title: "<atrás/além>",
        artist: "O Terno",
        image: "/music/atras-alem.webp",
        url: "https://open.spotify.com/album/5RHNy7sIVDOcLTsz4OeiwL",
      },
      {
        title: "Schlagenheim",
        artist: "black midi",
        image: "/music/schlagenheim.webp",
        url: "https://open.spotify.com/album/14LuwckQuyWIvVlKrYuLzP",
      },
      {
        title: "There Existed an Addiction to Blood",
        artist: "clipping.",
        image: "/music/there-existed-an-addiction-to-blood.webp",
        url: "https://open.spotify.com/album/1sJzod7aGgZwu2ShYec8GQ",
      },
      {
        title: "Resavoir",
        artist: "Resavoir",
        image: "/music/resavoir.webp",
        url: "https://open.spotify.com/album/7MjK7jYBy07G2GTCZgSzxd",
      },
    ],
  },
  {
    year: "2018",
    albums: [
      {
        title: "iridescence",
        artist: "BROCKHAMPTON",
        image: "/music/iridescence.webp",
        url: "https://open.spotify.com/album/3Mj4A4nNJzIdxOyS4yzOhj",
      },
      {
        title: "For Ever",
        artist: "Jungle",
        image: "/music/for-ever.webp",
        url: "https://open.spotify.com/album/1VZxGX1lzF1QjY5QofhC5r",
      },
      {
        title: "I'm All Ears",
        artist: "Let's Eat Grandma",
        image: "/music/i-m-all-ears.webp",
        url: "https://open.spotify.com/album/4TgXvHJWXGk0BlBvfs13Qg",
      },
      {
        title: "No New World",
        artist: "MASS OF THE FERMENTING DREGS",
        image: "/music/no-new-world.webp",
        url: "https://open.spotify.com/album/1Or7rQnUCdwz3NX5QFSIne",
      },
      {
        title: "KIDS SEE GHOSTS",
        artist: "KIDS SEE GHOSTS",
        image: "/music/kids-see-ghosts.webp",
        url: "https://open.spotify.com/album/6pwuKxMUkNg673KETsXPUV",
      },
      {
        title: "Wide Awake!",
        artist: "Parquet Courts",
        image: "/music/wide-awake.webp",
        url: "https://open.spotify.com/album/5uTI2HcpAywDP8Vo1DpJta",
      },
      {
        title: "Whack World",
        artist: "Tierra Whack",
        image: "/music/whack-world.webp",
        url: "https://open.spotify.com/album/3ogNAkUhvQy0cFOfLoR6Y8",
      },
      {
        title: "Dirty Computer",
        artist: "Janelle Monáe",
        image: "/music/dirty-computer.webp",
        url: "https://open.spotify.com/album/2PjlaxlMunGOUvcRzlTbtE",
      },
      {
        title: "Virtue",
        artist: "The Voidz",
        image: "/music/virtue.webp",
        url: "https://open.spotify.com/album/2dMmcXlG8xtRJNlsjIrPWe",
      },
      {
        title: "Little Dark Age",
        artist: "MGMT",
        image: "/music/little-dark-age.webp",
        url: "https://open.spotify.com/album/7GjVWG39IOj4viyWplJV4H",
      },
      {
        title: "Con Todo El Mundo",
        artist: "Khruangbin",
        image: "/music/con-todo-el-mundo.webp",
        url: "https://open.spotify.com/album/09AkhNYWocEZWbeYl1YBf7",
      },
      {
        title: "The Weather",
        artist: "Pond",
        image: "/music/the-weather.webp",
        url: "https://open.spotify.com/album/3N9tV0l74lqxcBegMv80S7",
      },
      {
        title: "Sex & Food",
        artist: "Unknown Mortal Orchestra",
        image: "/music/sex-food.webp",
        url: "https://open.spotify.com/album/7c2Xfq7aQKzs0KdSI3K7Rc",
      },
      {
        title: "Isolation",
        artist: "Kali Uchis",
        image: "/music/isolation.webp",
        url: "https://open.spotify.com/album/4EPQtdq6vvwxuYeQTrwDVY",
      },
      {
        title: "7",
        artist: "Beach House",
        image: "/music/7.webp",
        url: "https://open.spotify.com/album/65bVa55LFhY4PLx0kg8LjW",
      },
      {
        title: "Twin Fantasy",
        artist: "Car Seat Headrest",
        image: "/music/twin-fantasy.webp",
        url: "https://open.spotify.com/album/20U1UWeGcGq7JVW0tf8yfH",
      },
      {
        title: "Parcels",
        artist: "Parcels",
        image: "/music/parcels.webp",
        url: "https://open.spotify.com/album/6tNAnVG8xrmMbINuWutrNy",
      },
      {
        title: "You Won't Get What You Want",
        artist: "Daughters",
        image: "/music/you-won-t-get-what-you-want.webp",
        url: "https://open.spotify.com/album/21wg2jYkGO5RcnU2CV2a2s",
      },
      {
        title: "Veteran",
        artist: "JPEGMAFIA",
        image: "/music/veteran.webp",
        url: "https://open.spotify.com/album/22LKdgY3vLsAsWrOafwCM3",
      },
      {
        title: "Jassbusters",
        artist: "Connan Mockasin",
        image: "/music/jassbusters.webp",
        url: "https://open.spotify.com/album/5ZP4lqYPHwINHourSdZvYr",
      },
      {
        title: "Lost & Found",
        artist: "Jorja Smith",
        image: "/music/lost-found.webp",
        url: "https://open.spotify.com/album/3AlSuZnX4ZCab8eoWnnfbm",
      },
    ],
  },
  {
    year: "2017",
    albums: [
      {
        title: "Apricot Princess",
        artist: "Rex Orange County",
        image: "/music/apricot-princess.webp",
        url: "https://open.spotify.com/album/2NBVxjZcbH5H1N1Ab2ExDH",
      },
      {
        title: "Polygondwanaland",
        artist: "King Gizzard & The Lizard Wizard",
        image: "/music/polygondwanaland.webp",
        url: "https://open.spotify.com/album/6FAntlrL2g642UbLj66GTi",
      },
      {
        title: "Phase",
        artist: "Mildlife",
        image: "/music/phase.webp",
        url: "https://open.spotify.com/album/12zGIRwGNFH74714QX90W6",
      },
      {
        title: "Prince of Tears",
        artist: "Baxter Dury",
        image: "/music/prince-of-tears.webp",
        url: "https://open.spotify.com/album/3qb5B25qWfVjvWzFVmci0f",
      },
      {
        title: "4eva Is A Mighty Long Time",
        artist: "Big K.R.I.T.",
        image: "/music/4eva-is-a-mighty-long-time.webp",
        url: "https://open.spotify.com/album/6vGEX2ejVVsHTIsqI1teZg",
      },
      {
        title: "Mura Masa",
        artist: "Mura Masa",
        image: "/music/mura-masa.webp",
        url: "https://open.spotify.com/album/0NBTBo1qrg554sAj79nEqD",
      },
      {
        title: "How Did We Get So Dark?",
        artist: "Royal Blood",
        image: "/music/how-did-we-get-so-dark.webp",
        url: "https://open.spotify.com/album/3Rz6kF8eGqrDOEteo5YsBj",
      },
      {
        title: "The OOZ",
        artist: "King Krule",
        image: "/music/the-ooz.webp",
        url: "https://open.spotify.com/album/2Xx8ZUbuoyKnDgHh6Ot4xk",
      },
      {
        title: "Flower Boy",
        artist: "Tyler, The Creator",
        image: "/music/flower-boy.webp",
        url: "https://open.spotify.com/album/2nkto6YNI4rUYTLqEwWJ3o",
      },
      {
        title: "3:33am",
        artist: "Amber Mark",
        image: "/music/3-33am.webp",
        url: "https://open.spotify.com/album/0Yo1LADdOR5RZtkilf891i",
      },
      {
        title: "Universal High",
        artist: "Childhood",
        image: "/music/universal-high.webp",
        url: "https://open.spotify.com/album/0rigKScunOtcgNHU22KY5z",
      },
      {
        title: "Somersault",
        artist: "Beach Fossils",
        image: "/music/somersault.webp",
        url: "https://open.spotify.com/album/6Kkz3vJXJzemMSQkbsqWQR",
      },
      {
        title: "Pure Comedy",
        artist: "Father John Misty",
        image: "/music/pure-comedy.webp",
        url: "https://open.spotify.com/album/2QgZA6t1oFOjiJ59x7jrEI",
      },
      {
        title: "This Old Dog",
        artist: "Mac DeMarco",
        image: "/music/this-old-dog.webp",
        url: "https://open.spotify.com/album/6XzoFb3hP14jVQeCMRdVJR",
      },
      {
        title: "Antisocialites",
        artist: "Alvvays",
        image: "/music/antisocialites.webp",
        url: "https://open.spotify.com/album/5TGZvGolR6PoM1zYYyZNzX",
      },
      {
        title: "Crack-Up",
        artist: "Fleet Foxes",
        image: "/music/crack-up.webp",
        url: "https://open.spotify.com/album/0xtTojp4zfartyGtbFKN3v",
      },
      {
        title: "Soft Sounds from Another Planet",
        artist: "Japanese Breakfast",
        image: "/music/soft-sounds-from-another-planet.webp",
        url: "https://open.spotify.com/album/6AOaqWipm2Zk0oBp0uUey2",
      },
      {
        title: "Capacity",
        artist: "Big Thief",
        image: "/music/capacity.webp",
        url: "https://open.spotify.com/album/2hOYLjoRQFXcdviMiwtgxe",
      },
      {
        title: "Drunk",
        artist: "Thundercat",
        image: "/music/drunk.webp",
        url: "https://open.spotify.com/album/0pP7fWQxwXJ52FsQww0YGx",
      },
      {
        title: "Antiphon",
        artist: "Alfa Mist",
        image: "/music/antiphon.webp",
        url: "https://open.spotify.com/album/3yvubzjqmhnZhVwp6qDXPq",
      },
      {
        title: "Big Fish Theory",
        artist: "Vince Staples",
        image: "/music/big-fish-theory.webp",
        url: "https://open.spotify.com/album/5h3WJG0aZjNOrayFu3MhCS",
      },
    ],
  },
  {
    year: "2016",
    albums: [
      {
        title: "Blonde",
        artist: "Frank Ocean",
        image: "/music/blonde.webp",
        url: "https://open.spotify.com/album/1PDX0hMmsSdq122EupvNZF",
      },
      {
        title: '"Awaken, My Love!"',
        artist: "Childish Gambino",
        image: "/music/blonde.webp",
        url: "https://open.spotify.com/album/4Carzsnpd6yvuHZ49I0oz8",
      },
      {
        title: "American Boyfriend: A Suburban Love Story",
        artist: "Kevin Abstract",
        image: "/music/american-boyfriend-a-suburban-love-story.webp",
        url: "https://open.spotify.com/album/1yyCXBEu27Ia1Y3torWIwC",
      },
      {
        title: "Being No One, Going Nowhere",
        artist: "STRFKR",
        image: "/music/being-no-one-going-nowhere.webp",
        url: "https://open.spotify.com/album/2Atz9f2tBNGwjQEuOsYayk",
      },
      {
        title: "Black Focus",
        artist: "Yussef Kamaal",
        image: "/music/black-focus.webp",
        url: "https://open.spotify.com/album/0CAXEcXpruvyGKSTjyLDNu",
      },
      {
        title: "Lewis Del Mar",
        artist: "Lewis Del Mar",
        image: "/music/lewis-del-mar.webp",
        url: "https://open.spotify.com/album/7BKGTpCWDwTCeHnlLFcfLJ",
      },
      {
        title: "Mediterrâneo",
        artist: "Valter Lobo",
        image: "/music/mediterraneo.webp",
        url: "https://open.spotify.com/album/5RwXL3PDUgwvBjAeTJrGRo",
      },
      {
        title: "22, A Million",
        artist: "Bon Iver",
        image: "/music/22-a-million.webp",
        url: "https://open.spotify.com/album/1PgfRdl3lPyACfUGH4pquG",
      },
      {
        title: "MY WOMAN",
        artist: "Angel Olsen",
        image: "/music/my-woman.webp",
        url: "https://open.spotify.com/album/5M8xQaQZuW2LZGVXZ3mlKN",
      },
      {
        title: "IV",
        artist: "BADBADNOTGOOD",
        image: "/music/iv.webp",
        url: "https://open.spotify.com/album/6R7CVG0kOF7h0NLg10ezpZ",
      },
      {
        title: "99.9%",
        artist: "KAYTRANADA",
        image: "/music/99-9.webp",
        url: "https://open.spotify.com/album/1dZZh7PvVgce1DDsDPzy8Z",
      },
      {
        title: "Nonagon Infinity",
        artist: "King Gizzard & The Lizard Wizard",
        image: "/music/nonagon-infinity.webp",
        url: "https://open.spotify.com/album/7hpznmwqB8FM05bEpN9P94",
      },
      {
        title: "Atomic",
        artist: "Mogwai",
        image: "/music/atomic.webp",
        url: "https://open.spotify.com/album/0CqzNvp9W9Dl3oMU9SWIkT",
      },
      {
        title: "III",
        artist: "Moderat",
        image: "/music/iii-2.webp",
        url: "https://open.spotify.com/album/7BmMOUo8nrmYHB2EHBGkSt",
      },
      {
        title: "Telefone",
        artist: "Noname",
        image: "/music/telefone.webp",
        url: "https://open.spotify.com/album/18Scpsg5OV1iYNtSaCsjwz",
      },
      {
        title: "Those Who Throw Objects at the Crocodiles Will Be Asked to Retrieve Them",
        artist: "Bruno Pernadas",
        image:
          "/music/those-who-throw-objects-at-the-crocodiles-will-be-asked-to-retrieve-them.webp",
        url: "https://open.spotify.com/album/2NYnAb4TkXGHrY8wZ9uZwT",
      },
      {
        title: "The Life Of Pablo",
        artist: "Kanye West",
        image: "/music/the-life-of-pablo.webp",
        url: "https://open.spotify.com/album/7gsWAHLeT0w7es6FofOXk1",
      },
      {
        title: "A Moon Shaped Pool",
        artist: "Radiohead",
        image: "/music/a-moon-shaped-pool.webp",
        url: "https://open.spotify.com/album/6vuykQgDLUCiZ7YggIpLM9",
      },
      {
        title: "Light Upon the Lake",
        artist: "Whitney",
        image: "/music/light-upon-the-lake.webp",
        url: "https://open.spotify.com/album/5yMCA6HdFAeL1aqUjxO3MO",
      },
      {
        title: "Princesa",
        artist: "Carne Doce",
        image: "/music/princesa.webp",
        url: "https://open.spotify.com/album/3krb3LsOogMryKOllCsYAL",
      },
      {
        title: "Teens Of Denial",
        artist: "Car Seat Headrest",
        image: "/music/teens-of-denial.webp",
        url: "https://open.spotify.com/album/0czBomMxaMCzanUaFhESOW",
      },
    ],
  },
  {
    year: "2015",
    albums: [
      {
        title: "Tell Me I'm Pretty",
        artist: "Cage The Elephant",
        image: "/music/tell-me-i-m-pretty.webp",
        url: "https://open.spotify.com/album/0nW0w37lrQ87k7PLZvC4qJ",
      },
      {
        title: "Paper Mâché Dream Balloon",
        artist: "King Gizzard & The Lizard Wizard",
        image: "/music/paper-mache-dream-balloon.webp",
        url: "https://open.spotify.com/album/6upVMLoNWxRF5Ahrd8YGF2",
      },
      {
        title: "<I°_°I>",
        artist: "Caravan Palace",
        image: "/music/i-i.webp",
        url: "https://open.spotify.com/album/3LBVVeFs1R0VJobVUzNSdx",
      },
      {
        title: "The Future Sugar",
        artist: "Rey Pila",
        image: "/music/the-future-sugar.webp",
        url: "https://open.spotify.com/album/1k4iFJs342EvXCEqQ3kt3V",
      },
      {
        title: "Midnight Snack",
        artist: "HOMESHAKE",
        image: "/music/midnight-snack.webp",
        url: "https://open.spotify.com/album/4p7OubIrnoRbhi3YUbN5Ib",
      },
      {
        title: "Depression Cherry",
        artist: "Beach House",
        image: "/music/depression-cherry.webp",
        url: "https://open.spotify.com/album/4SkZTSXdPpzTbf6C0m1UKv",
      },
      {
        title: "Currents",
        artist: "Tame Impala",
        image: "/music/currents.webp",
        url: "https://open.spotify.com/album/79dL7FLiJFOO0EoehUHQBv",
      },
      {
        title: "Get To Heaven",
        artist: "Everything Everything",
        image: "/music/get-to-heaven.webp",
        url: "https://open.spotify.com/album/1oScYOf8ImO6L9bdvhep1J",
      },
      {
        title: "Hasta La Raíz",
        artist: "Natalia Lafourcade",
        image: "/music/hasta-la-raiz.webp",
        url: "https://open.spotify.com/album/6DWTUm9rifRvl5PTyNMwqV",
      },
      {
        title: "Weird Little Birthday",
        artist: "Happyness",
        image: "/music/weird-little-birthday.webp",
        url: "https://open.spotify.com/album/24jYrXKPwQrnzcy0qyLhYs",
      },
      {
        title: "Carrie & Lowell",
        artist: "Sufjan Stevens",
        image: "/music/carrie-lowell.webp",
        url: "https://open.spotify.com/album/0U8DeqqKDgIhIiWOdqiQXE",
      },
      {
        title: "Have You In My Wilderness",
        artist: "Julia Holter",
        image: "/music/have-you-in-my-wilderness.webp",
        url: "https://open.spotify.com/album/1kVTV6AoeMjAOMOJyVfYOl",
      },
      {
        title: "Multi-Love",
        artist: "Unknown Mortal Orchestra",
        image: "/music/multi-love.webp",
        url: "https://open.spotify.com/album/2aoI8tkPq9NBvGiARD0KoR",
      },
      {
        title: "Fading Frontier",
        artist: "Deerhunter",
        image: "/music/fading-frontier.webp",
        url: "https://open.spotify.com/album/0y5XgOUEiJSSIMxC4ALRAC",
      },
      {
        title: "Solo",
        artist: "Nils Frahm",
        image: "/music/solo.webp",
        url: "https://open.spotify.com/album/7eC6sBSIM2MgWdpywd90iU",
      },
      {
        title: "Reflektor",
        artist: "Arcade Fire",
        image: "/music/reflektor.webp",
        url: "https://open.spotify.com/album/2brwuyGZ2lLqWnBX6U4MQT",
      },
      {
        title: "The Universe Smiles Upon You",
        artist: "Khruangbin",
        image: "/music/the-universe-smiles-upon-you.webp",
        url: "https://open.spotify.com/album/2OPcQNLP8DQVumD8kBRAH3",
      },
      {
        title: "Joy, Departed",
        artist: "Sorority Noise",
        image: "/music/joy-departed.webp",
        url: "https://open.spotify.com/album/0QS65kaBpmHYzVoyhIKXfJ",
      },
    ],
  },
  {
    year: "2014",
    albums: [
      {
        title: "To Be Kind",
        artist: "Swans",
        image: "/music/to-be-kind.webp",
        url: "https://open.spotify.com/album/1WwiyWxa40PKucRxIKlEVM",
      },
      {
        title: "Piñata",
        artist: "Freddie Gibbs, Madlib",
        image: "/music/pinata.webp",
        url: "https://open.spotify.com/album/43uErencdmuTRFZPG3zXL1",
      },
      {
        title: "Faces",
        artist: "Mac Miller",
        image: "/music/faces.webp",
        url: "https://open.spotify.com/album/5SKnXCvB4fcGSZu32o3LRY",
      },
      {
        title: "Sylvan Esso",
        artist: "Sylvan Esso",
        image: "/music/sylvan-esso.webp",
        url: "https://open.spotify.com/album/5Abelpx4c3FzhTOZP3ZIvS",
      },
      {
        title: "Too Bright",
        artist: "Perfume Genius",
        image: "/music/too-bright.webp",
        url: "https://open.spotify.com/album/5qtHbJAK0C1IkacqJBqsa2",
      },
      {
        title: "Cavalo",
        artist: "Rodrigo Amarante",
        image: "/music/cavalo.webp",
        url: "https://open.spotify.com/album/31ztYM5ZqVNKZolLUrVtug",
      },
      {
        title: "Are We There",
        artist: "Sharon Van Etten",
        image: "/music/are-we-there.webp",
        url: "https://open.spotify.com/album/69EhwEgjEWQ8GqH7wqEndn",
      },
      {
        title: "Wlfgrl",
        artist: "Machine Girl",
        image: "/music/wlfgrl.webp",
        url: "https://open.spotify.com/album/1xbcqJ0EAMxyGyffMzO8rL",
      },
      {
        title: "Kiasmos",
        artist: "Kiasmos",
        image: "/music/kiasmos.webp",
        url: "https://open.spotify.com/album/7pBDu7nc2KaMsh0SfZMc2d",
      },
      {
        title: "Salad Days",
        artist: "Mac DeMarco",
        image: "/music/salad-days.webp",
        url: "https://open.spotify.com/album/7xPhDaYZ2ejV04aNtdBdvj",
      },
      {
        title: "Odyssey",
        artist: "Home",
        image: "/music/odyssey.webp",
        url: "https://open.spotify.com/album/6aZyHNR0hqCSd3WZZdKt0B",
      },
      {
        title: "Singles",
        artist: "Future Islands",
        image: "/music/singles.webp",
        url: "https://open.spotify.com/album/1dKh4z5Aayt8FFDWjO5FDh",
      },
      {
        title: "Alvvays",
        artist: "Alvvays",
        image: "/music/alvvays.webp",
        url: "https://open.spotify.com/album/1j3pIPXjLIFkp84OfVUsNT",
      },
      {
        title: "Our Love",
        artist: "Caribou",
        image: "/music/our-love.webp",
        url: "https://open.spotify.com/album/233jGebCTUPAYF5MxvLB7A",
      },
      {
        title: "III",
        artist: "BADBADNOTGOOD",
        image: "/music/iii.webp",
        url: "https://open.spotify.com/album/4fKloYEEuG3ckFoOF8glRj",
      },
      {
        title: "French Exit",
        artist: "TV Girl",
        image: "/music/french-exit.webp",
        url: "https://open.spotify.com/album/6WrxgVbi9Q96gV8tZMq3FH",
      },
      {
        title: "ZABA",
        artist: "Glass Animals",
        image: "/music/zaba.webp",
        url: "https://open.spotify.com/album/7jfkffCqKYEJmIgGOIJ9me",
      },
      {
        title: "Couch",
        artist: "Blowfuse",
        image: "/music/couch.webp",
        url: "https://open.spotify.com/album/4IJ5f6J9owLts8uGxYnx66",
      },
      {
        title: "This Is All Yours",
        artist: "alt-J",
        image: "/music/this-is-all-yours.webp",
        url: "https://open.spotify.com/album/6TbkWAqqY4nhQnYim61IU8",
      },
      {
        title: "Royal Blood",
        artist: "Royal Blood",
        image: "/music/royal-blood.webp",
        url: "https://open.spotify.com/album/0BFzNaeaNv4mahOzwZFGHK",
      },
      {
        title: "Jungle",
        artist: "Jungle",
        image: "/music/jungle.webp",
        url: "https://open.spotify.com/album/6IH6co1QUS7uXoyPDv0rIr",
      },
      {
        title: "First Mind",
        artist: "Nick Mulvey",
        image: "/music/first-mind.webp",
        url: "https://open.spotify.com/album/0ntJpgznXrZ6Qc8wTxtcXh",
      },
      {
        title: "Morning Phase",
        artist: "Beck",
        image: "/music/morning-phase.webp",
        url: "https://open.spotify.com/album/3BBFUxPg8KFmAv96SmY4ok",
      },
      {
        title: "Do Princípio",
        artist: "Tiago Bettencourt",
        image: "/music/do-principio.webp",
        url: "https://open.spotify.com/album/7cYv9V8cH4EAUmOnk3zGkW",
      },
    ],
  },
  {
    year: "2013",
    albums: [
      {
        title: "We Are the 21st Century Ambassadors of Peace & Magic",
        artist: "Foxygen",
        image: "/music/we-are-the-21st-century-ambassadors-of-peace-magic.webp",
        url: "https://open.spotify.com/album/7FfiN9ztbjLNPWhuhFHaWf",
      },
      {
        title: "Melophobia",
        artist: "Cage The Elephant",
        image: "/music/melophobia.webp",
        url: "https://open.spotify.com/album/0H6DSMuGSRC25Ka7PE4O4q",
      },
      {
        title: "AM",
        artist: "Arctic Monkeys",
        image: "/music/am.webp",
        url: "https://open.spotify.com/album/5bU1XKYxHhEwukllT20xtk",
      },
      {
        title: "Fuzz",
        artist: "Fuzz",
        image: "/music/fuzz.webp",
        url: "https://open.spotify.com/album/1D3YttJsWvUUSvOVRbic0o",
      },
      {
        title: "Tawk Tomahawk",
        artist: "Hiatus Kaiyote",
        image: "/music/tawk-tomahawk.webp",
        url: "https://open.spotify.com/album/54UDcBALhfyaQ67fsSZrkQ",
      },
      {
        title: "Kveikur",
        artist: "Sigur Rós",
        image: "/music/kveikur.webp",
        url: "https://open.spotify.com/album/1rRNqn4MTZfh393GzGvBtY",
      },
      {
        title: "Trouble Will Find Me",
        artist: "The National",
        image: "/music/trouble-will-find-me.webp",
        url: "https://open.spotify.com/album/2JhR4tjuc3MIKa8v2JaKze",
      },
      {
        title: "Evil Friends",
        artist: "Portugal. The Man",
        image: "/music/evil-friends.webp",
        url: "https://open.spotify.com/album/6VoOCCv0bXPrTHDncJyIgF",
      },
      {
        title: "Night Time, My Time",
        artist: "Sky Ferreira",
        image: "/music/night-time-my-time.webp",
        url: "https://open.spotify.com/album/0DucmDrdJM4evPXMbFJXBS",
      },
      {
        title: "II",
        artist: "Unknown Mortal Orchestra",
        image: "/music/ii-2.webp",
        url: "https://open.spotify.com/album/41C5iULlHU9sMYiekI75Pn",
      },
      {
        title: "Random Access Memories",
        artist: "Daft Punk",
        image: "/music/random-access-memories.webp",
        url: "https://open.spotify.com/album/4m2880jivSbbyEGAKfITCa",
      },
      {
        title: "Yeezus",
        artist: "Kanye West",
        image: "/music/yeezus.webp",
        url: "https://open.spotify.com/album/0XTAmejG8F97wF5MWoVbaY",
      },
      {
        title: "Overgrown",
        artist: "James Blake",
        image: "/music/overgrown.webp",
        url: "https://open.spotify.com/album/12ExNn0hx85F8UNzoKCyCD",
      },
      {
        title: "II",
        artist: "Moderat",
        image: "/music/ii.webp",
        url: "https://open.spotify.com/album/4QNlqYSMYCPiKZfzUfH7jK",
      },
      {
        title: "Woman",
        artist: "Rhye",
        image: "/music/woman.webp",
        url: "https://open.spotify.com/album/6b1HPtDuYioXwmw5xLLFQ9",
      },
      {
        title: "Mala",
        artist: "Devendra Banhart",
        image: "/music/mala.webp",
        url: "https://open.spotify.com/album/1Z69PSnbIBojgF9NBJbKca",
      },
      {
        title: "AMOK",
        artist: "Atoms For Peace",
        image: "/music/amok.webp",
        url: "https://open.spotify.com/album/6dJZDZMNdBPZrJcNv57bEq",
      },
      {
        title: "Miracle Mile",
        artist: "STRFKR",
        image: "/music/miracle-mile.webp",
        url: "https://open.spotify.com/album/5S4tasGYxpQuSEWLYvgyQp",
      },
    ],
  },
  {
    year: "2012",
    albums: [
      {
        title: "The Seer",
        artist: "Swans",
        image: "/music/the-seer.webp",
        url: "https://open.spotify.com/album/1ijaW4mgV7Xz7DK5cXyjoo",
      },
      {
        title: "The Adventures of Mr. Fox",
        artist: "KOAN Sound",
        image: "/music/the-adventures-of-mr-fox.webp",
        url: "https://open.spotify.com/album/6HcxxnB2J6WODYFENqrLTa",
      },
      {
        title:
          "World Psychedelic Classics 4: Nobody Can Live Forever: The Existential Soul of Tim Maia",
        artist: "Tim Maia",
        image:
          "/music/world-psychedelic-classics-4-nobody-can-live-forever-the-existential-soul-of-tim-maia.webp",
        url: "https://open.spotify.com/album/59NOU4R72nphHRtwQlGfjJ",
      },
      {
        title: "The Money Store",
        artist: "Death Grips",
        image: "/music/the-money-store.webp",
        url: "https://open.spotify.com/album/1PQDjdBpHPikAodJqjzm6a",
      },
      {
        title: "Seven Thunders Roar",
        artist: "Stoned Jesus",
        image: "/music/seven-thunders-roar.webp",
        url: "https://open.spotify.com/album/5KEs1CBh2Keg4OMVsYfaZU",
      },
      {
        title: "Bloom",
        artist: "Beach House",
        image: "/music/bloom.webp",
        url: "https://open.spotify.com/album/600BVck2XflTAsEo0KhIfm",
      },
      {
        title: "Swing Lo Magellan",
        artist: "Dirty Projectors",
        image: "/music/swing-lo-magellan.webp",
        url: "https://open.spotify.com/album/5leXnIiFPYSr7yHgdwxMDG",
      },
      {
        title: "Beacon",
        artist: "Two Door Cinema Club",
        image: "/music/beacon.webp",
        url: "https://open.spotify.com/album/6CPwf8Yo8a4cgBDVeShL5C",
      },
      {
        title: "2",
        artist: "Mac DeMarco",
        image: "/music/2.webp",
        url: "https://open.spotify.com/album/7x6wYKbZUU2BL3N8ZWwM3q",
      },
      {
        title: "Lonerism",
        artist: "Tame Impala",
        image: "/music/lonerism.webp",
        url: "https://open.spotify.com/album/76vY9yohh4kVwSKkyKbyEQ",
      },
      {
        title: "channel ORANGE",
        artist: "Frank Ocean",
        image: "/music/channel-orange.webp",
        url: "https://open.spotify.com/album/623Ef2ZEB3Njklix4PC0Rs",
      },
      {
        title: "Shields",
        artist: "Grizzly Bear",
        image: "/music/shields.webp",
        url: "https://open.spotify.com/album/57LAEzKL94ZHwbIkUWYCDY",
      },
      {
        title: "Tetra",
        artist: "C2C",
        image: "/music/tetra.webp",
        url: "https://open.spotify.com/album/3bJg5G91aADhnnYNkMel3z",
      },
      {
        title: "Voyeur",
        artist: "Saint Motel",
        image: "/music/voyeur.webp",
        url: "https://open.spotify.com/album/24nqMCIROq1MULNqjzeglz",
      },
      {
        title: "Colourmeinkindness",
        artist: "Basement",
        image: "/music/colourmeinkindness.webp",
        url: "https://open.spotify.com/album/70yn72rS28G1jieaBHlZhY",
      },
      {
        title: "I.",
        artist: "Cigarettes After Sex",
        image: "/music/i.webp",
        url: "https://open.spotify.com/album/5GvLhLPpP03FuLvxgdEnpj",
      },
      {
        title: "good kid, m.A.A.d city (Deluxe)",
        artist: "Kendrick Lamar",
        image: "/music/good-kid-m-a-a-d-city-deluxe.webp",
        url: "https://open.spotify.com/album/1DqhWr73Fh5yoNzKLas0G3",
      },
      {
        title: "Coexist",
        artist: "The xx",
        image: "/music/coexist.webp",
        url: "https://open.spotify.com/album/2cRMVS71c49Pf5SnIlJX3U",
      },
      {
        title: "Sun",
        artist: "Cat Power",
        image: "/music/sun.webp",
        url: "https://open.spotify.com/album/1IoiJGsAHdL0OL9IOjTflm",
      },
    ],
  },
  {
    year: "2011",
    albums: [
      {
        title: "Kaputt",
        artist: "Destroyer",
        image: "/music/kaputt.webp",
        url: "https://open.spotify.com/album/4XuDhEQRnieTnCbeUu9GoR",
      },
      {
        title: "Helplessness Blues",
        artist: "Fleet Foxes",
        image: "/music/helplessness-blues.webp",
        url: "https://open.spotify.com/album/6SUzec8cWCUMhvdW3KbMYZ",
      },
      {
        title: "Angles",
        artist: "The Strokes",
        image: "/music/angles.webp",
        url: "https://open.spotify.com/album/6Jx4cGhWHewTcfKDJKguBQ",
      },
      {
        title: "Young The Giant",
        artist: "Young the Giant",
        image: "/music/young-the-giant.webp",
        url: "https://open.spotify.com/album/0SjFStr64eylrHDmZHGiTI",
      },
      {
        title: "Toque Dela",
        artist: "Marcelo Camelo",
        image: "/music/toque-dela.webp",
        url: "https://open.spotify.com/album/1NP7PX0MQPH6pLHr2R8e9K",
      },
      {
        title: "A Different Kind Of Fix",
        artist: "Bombay Bicycle Club",
        image: "/music/a-different-kind-of-fix.webp",
        url: "https://open.spotify.com/album/4W6ztwnEbK92Arl8kI9c9N",
      },
      {
        title: "Portamento",
        artist: "The Drums",
        image: "/music/portamento.webp",
        url: "https://open.spotify.com/album/1NAjWuELiyrM0RoQfNbHWb",
      },
      {
        title: "The English Riviera",
        artist: "Metronomy",
        image: "/music/the-english-riviera.webp",
        url: "https://open.spotify.com/album/716fnrS2qXChPC3J2X73pK",
      },
      {
        title: "Wasting Light",
        artist: "Foo Fighters",
        image: "/music/wasting-light.webp",
        url: "https://open.spotify.com/album/5lnQLEUiVDkLbFJHXHQu9m",
      },
      {
        title: "Forever Dolphin Love",
        artist: "Connan Mockasin",
        image: "/music/forever-dolphin-love.webp",
        url: "https://open.spotify.com/album/7s9NpXqhb6i0xsnIvMqI7j",
      },
      {
        title: "Never Trust a Happy Song",
        artist: "Grouplove",
        image: "/music/never-trust-a-happy-song.webp",
        url: "https://open.spotify.com/album/3oylWMc9TTC6Nx4I6U3axc",
      },
      {
        title: "Idle Labor",
        artist: "Craft Spells",
        image: "/music/idle-labor.webp",
        url: "https://open.spotify.com/album/3IzLouGQA5uY4NfT6zNe3j",
      },
      {
        title: "Torches",
        artist: "Foster The People",
        image: "/music/torches.webp",
        url: "https://open.spotify.com/album/7Kmmw7Z5D2UD5MVwdm10sT",
      },
      {
        title: "Life Is Full Of Possibilities (Deluxe)",
        artist: "Dntel",
        image: "/music/life-is-full-of-possibilities-deluxe.webp",
        url: "https://open.spotify.com/album/1UFMT6XephLvL7R2Rfb9dc",
      },
    ],
  },
  {
    year: "2010",
    albums: [
      {
        title: "My Beautiful Dark Twisted Fantasy",
        artist: "Kanye West",
        image: "/music/my-beautiful-dark-twisted-fantasy.webp",
        url: "https://open.spotify.com/album/20r762YmB5HeofjMCiPMLv",
      },
      {
        title: "Melted",
        artist: "Ty Segall",
        image: "/music/melted.webp",
        url: "https://open.spotify.com/album/5P0LN9xrnLY1By7mlkKtkx",
      },
      {
        title: "Gemini",
        artist: "Wild Nothing",
        image: "/music/gemini.webp",
        url: "https://open.spotify.com/album/2UoAYpQzSNLuW47goFJE5x",
      },
      {
        title: "InnerSpeaker",
        artist: "Tame Impala",
        image: "/music/innerspeaker.webp",
        url: "https://open.spotify.com/album/1DNSmmRLfv97Yjq7MTFWng",
      },
      {
        title: "Broken Bells",
        artist: "Broken Bells",
        image: "/music/broken-bells.webp",
        url: "https://open.spotify.com/album/0X7WyEKdm5afGj1fmD7Blx",
      },
      {
        title: "Plastic Beach",
        artist: "Gorillaz",
        image: "/music/plastic-beach.webp",
        url: "https://open.spotify.com/album/2dIGnmEIy1WZIcZCFSj6i8",
      },
      {
        title: "Hooray! For Happiness",
        artist: "The Last Dinosaur",
        image: "/music/hooray-for-happiness.webp",
        url: "https://open.spotify.com/album/711BUAij7FQyF93WPaBuh8",
      },
      {
        title: "Teen Dream",
        artist: "Beach House",
        image: "/music/teen-dream.webp",
        url: "https://open.spotify.com/album/5BouX39qnrl5UxjB0Cs3lO",
      },
      {
        title: "剃刀乙女",
        artist: "Ichiko Aoba",
        image: "/music/image-3.webp",
        url: "https://open.spotify.com/album/1lpxxmRaI4loziFL9USol5",
      },
      {
        title: "The Fall",
        artist: "Gorillaz",
        image: "/music/the-fall.webp",
        url: "https://open.spotify.com/album/5jJGGsAztgUEXUHHZ2zrah",
      },
      {
        title: "Heligoland",
        artist: "Massive Attack",
        image: "/music/heligoland.webp",
        url: "https://open.spotify.com/album/1F8y2bg9V9nRoy8zuxo3Jt",
      },
    ],
  },
  {
    year: "2009",
    albums: [
      {
        title: "Moderat",
        artist: "Moderat",
        image: "/music/moderat.webp",
        url: "https://open.spotify.com/album/2HEh23ogCT3wiYfag2iMxD",
      },
      {
        title: "Study Guide",
        artist: "Question & Freddie Joachim",
        image: "/music/study-guide.webp",
        url: "https://open.spotify.com/album/46LudqPGBEIX9l8FlVqe9x",
      },
      {
        title: "Fever Ray",
        artist: "Fever Ray",
        image: "/music/fever-ray.webp",
        url: "https://open.spotify.com/album/0ixCVTYtBghqNKuGP1a9om",
      },
      {
        title: "I Had The Blues But I Shook Them Loose",
        artist: "Bombay Bicycle Club",
        image: "/music/i-had-the-blues-but-i-shook-them-loose.webp",
        url: "https://open.spotify.com/album/4X0bhkSBOfcnOPyfG5Ef6a",
      },
      {
        title: "Drift",
        artist: "Nosaj Thing",
        image: "/music/drift.webp",
        url: "https://open.spotify.com/album/5hAYGaI45A3xyfyztCQV5j",
      },
      {
        title: "Album",
        artist: "Girls",
        image: "/music/album.webp",
        url: "https://open.spotify.com/album/1csBXckSWxkPEUXT4nSeP3",
      },
    ],
  },
  {
    year: "2008",
    albums: [
      {
        title: "Deathconsciousness",
        artist: "Have A Nice Life",
        image: "/music/deathconsciousness.webp",
        url: "https://open.spotify.com/album/6MH3CAXp8AN8ELrbex18dM",
      },
      {
        title: "O Amor dá-Me Tesão / Não Fui Eu Que Estraguei",
        artist: "Foge Foge Bandido",
        image: "/music/o-amor-da-me-tesao-nao-fui-eu-que-estraguei.webp",
        url: "https://open.spotify.com/album/0yDcbYfuf4V3aJ5SmtlQIY",
      },
      {
        title: "Fleet Foxes",
        artist: "Fleet Foxes",
        image: "/music/fleet-foxes.webp",
        url: "https://open.spotify.com/album/1rfgmU0AYNwWfS88pCOlX7",
      },
      {
        title: "Starfucker",
        artist: "STRFKR",
        image: "/music/starfucker.webp",
        url: "https://open.spotify.com/album/4mBSeOEiQ4WgDaCnydb0tZ",
      },
      {
        title: "The Sparrow and the Crow",
        artist: "William Fitzsimmons",
        image: "/music/the-sparrow-and-the-crow.webp",
        url: "https://open.spotify.com/album/2DjhgnwjDunba78KGvCcoK",
      },
      {
        title: "808s & Heartbreak",
        artist: "Kanye West",
        image: "/music/808s-heartbreak.webp",
        url: "https://open.spotify.com/album/3WFTGIO6E3Xh4paEOBY9OU",
      },
    ],
  },
  {
    year: "2007",
    albums: [
      {
        title: "Ga Ga Ga Ga Ga",
        artist: "Spoon",
        image: "/music/ga-ga-ga-ga-ga.webp",
        url: "https://open.spotify.com/album/6zEGEx2ZXpiLczrpu5wWqu",
      },
      {
        title: "In Rainbows",
        artist: "Radiohead",
        image: "/music/in-rainbows.webp",
        url: "https://open.spotify.com/album/5vkqYmiPBYLaalcmjujWxK",
      },
      {
        title: "Oracular Spectacular",
        artist: "MGMT",
        image: "/music/oracular-spectacular.webp",
        url: "https://open.spotify.com/album/6mm1Skz3JE6AXneya9Nyiv",
      },
      {
        title: "Little Dragon",
        artist: "Little Dragon",
        image: "/music/little-dragon.webp",
        url: "https://open.spotify.com/album/34AtsFexhxnKPVJFtLIN1I",
      },
      {
        title: "Justice",
        artist: "Justice",
        image: "/music/justice.webp",
        url: "https://open.spotify.com/album/4GGazqHvuKwxBjWLFaJkDL",
      },
      {
        title: "Minutes to Midnight",
        artist: "Linkin Park",
        image: "/music/minutes-to-midnight.webp",
        url: "https://open.spotify.com/album/7pgs38iLfEqUtwgCRgvbND",
      },
      {
        title: "Vista Point",
        artist: "Yawning Man",
        image: "/music/vista-point.webp",
        url: "https://open.spotify.com/album/63j1bHAkaHjUU6l6WyODiw",
      },
      {
        title: "S/T",
        artist: "This Will Destroy You",
        image: "/music/s-t.webp",
        url: "https://open.spotify.com/album/72vAmnfrNfzORX6gG7p8Jf",
      },
      {
        title: "Favourite Worst Nightmare",
        artist: "Arctic Monkeys",
        image: "/music/favourite-worst-nightmare.webp",
        url: "https://open.spotify.com/album/1XkGORuUX2QGOEIL4EbJKm",
      },
      {
        title: "The Shepherd's Dog",
        artist: "Iron & Wine",
        image: "/music/the-shepherd-s-dog.webp",
        url: "https://open.spotify.com/album/3cgyaeNsyR71FvHTPH5v3u",
      },
    ],
  },
  {
    year: "2006",
    albums: [
      {
        title: "Olhos De Mongol",
        artist: "Linda Martini",
        image: "/music/olhos-de-mongol.webp",
        url: "https://open.spotify.com/album/6hDZhsdeMstnFgd9AiWnJy",
      },
      {
        title: "Goodnight",
        artist: "William Fitzsimmons",
        image: "/music/goodnight.webp",
        url: "https://open.spotify.com/album/4mNpxvAvj2ay7Vat4pfEFI",
      },
      {
        title: "10,000 Days",
        artist: "TOOL",
        image: "/music/10-000-days.webp",
        url: "https://open.spotify.com/album/1fvWYcbjuycyHpzNPH1Vfk",
      },
    ],
  },
  {
    year: "2005",
    albums: [
      {
        title: "Modal Soul",
        artist: "Nujabes",
        image: "/music/modal-soul.webp",
        url: "https://open.spotify.com/album/6nVACH6a27eOWiumAJhDWS",
      },
      {
        title: "The Life Aquatic Exclusive Studio Sessions Featuring Seu Jorge",
        artist: "Seu Jorge",
        image: "/music/the-life-aquatic-exclusive-studio-sessions-featuring-seu-jorge.webp",
        url: "https://open.spotify.com/album/2tAFOhqz3DxxVI2s5YNsrD",
      },
      {
        title: "Neveroddoreven",
        artist: "I Monster",
        image: "/music/neveroddoreven.webp",
        url: "https://open.spotify.com/album/4qD7h4hXvmKT49wDrN2kLE",
      },
      {
        title: "Illinois",
        artist: "Sufjan Stevens",
        image: "/music/illinois.webp",
        url: "https://open.spotify.com/album/1pOl0KEC1iQnA6F0XxV4To",
      },
      {
        title: "Demon Days",
        artist: "Gorillaz",
        image: "/music/demon-days.webp",
        url: "https://open.spotify.com/album/0bUTHlWbkSQysoM3VsWldT",
      },
      {
        title: "Late Registration",
        artist: "Kanye West",
        image: "/music/late-registration.webp",
        url: "https://open.spotify.com/album/5ll74bqtkcXlKE7wwkMq4g",
      },
      {
        title: "Céu",
        artist: "Céu",
        image: "/music/ceu.webp",
        url: "https://open.spotify.com/album/17jh7tYL1hiAltz0DJlvLN",
      },
      {
        title: "From mars to sirius",
        artist: "Gojira",
        image: "/music/from-mars-to-sirius.webp",
        url: "https://open.spotify.com/album/0AvFF0HlQYvYKHaRURGZBs",
      },
      {
        title: "Frances the Mute",
        artist: "The Mars Volta",
        image: "/music/frances-the-mute.webp",
        url: "https://open.spotify.com/album/30iqYID1JMBXLVFfErwTSd",
      },
      {
        title: "Team Sleep (U.S. Release)",
        artist: "Team Sleep",
        image: "/music/team-sleep-u-s-release.webp",
        url: "https://open.spotify.com/album/7BORauiIbjPkOVRzSq38DP",
      },
    ],
  },
  {
    year: "2004",
    albums: [
      {
        title: "Hot Fuss",
        artist: "The Killers",
        image: "/music/hot-fuss.webp",
        url: "https://open.spotify.com/album/1ujPmNlTMp41h4EG6OOBGR",
      },
      {
        title: "Madvillainy",
        artist: "Madvillain, Madlib, MF DOOM",
        image: "/music/madvillainy.webp",
        url: "https://open.spotify.com/album/01FCoGEQ3NFWF4fHJzdiax",
      },
      {
        title: "When It Falls",
        artist: "Zero 7",
        image: "/music/when-it-falls.webp",
        url: "https://open.spotify.com/album/0rZ4eyogYJlxLevP1Wm1b6",
      },
      {
        title: "MM...FOOD",
        artist: "MF DOOM",
        image: "/music/mm-food.webp",
        url: "https://open.spotify.com/album/7IvmRtuLsTlRZhRS6KUQRn",
      },
      {
        title: "Spirals in Hyperspace",
        artist: "Ozric Tentacles",
        image: "/music/spirals-in-hyperspace.webp",
        url: "https://open.spotify.com/album/7EVKKZMWphUwkGzntYSnEz",
      },
      {
        title: "Bom Dia",
        artist: "Pluto",
        image: "/music/bom-dia.webp",
        url: "https://open.spotify.com/album/4hUEJkl2B87nVy9pby0OZv",
      },
      {
        title: "Talkie Walkie",
        artist: "Air",
        image: "/music/talkie-walkie.webp",
        url: "https://open.spotify.com/album/0hQOqvZv1nQvPiBjzyn363",
      },
    ],
  },
  {
    year: "2003",
    albums: [
      {
        title: "Metaphorical Music",
        artist: "Nujabes",
        image: "/music/metaphorical-music.webp",
        url: "https://open.spotify.com/album/5FrjDW96mCYw9ECc74c637",
      },
      {
        title: "Room On Fire",
        artist: "The Strokes",
        image: "/music/room-on-fire.webp",
        url: "https://open.spotify.com/album/3HFbH1loOUbqCyPsLuHLLh",
      },
      {
        title: "You Forgot It In People",
        artist: "Broken Social Scene",
        image: "/music/you-forgot-it-in-people.webp",
        url: "https://open.spotify.com/album/6nL0U84JsEJ0cRsGCnsDnJ",
      },
      {
        title: "Velocity: Design: Comfort.",
        artist: "Sweet Trip",
        image: "/music/velocity-design-comfort.webp",
        url: "https://open.spotify.com/album/0eUUQ4rly8Q8PyJPWLgde2",
      },
      {
        title: "Happy Songs For Happy People",
        artist: "Mogwai",
        image: "/music/happy-songs-for-happy-people.webp",
        url: "https://open.spotify.com/album/1FvIoulivmS5n4Kp3zpBr2",
      },
      {
        title: "Dopesmoker",
        artist: "Sleep",
        image: "/music/dopesmoker.webp",
        url: "https://open.spotify.com/album/1u49hpxNCoTCWmJa1NXUZl",
      },
    ],
  },
  {
    year: "2002",
    albums: [
      {
        title: "The Richest Man In Babylon",
        artist: "Thievery Corporation",
        image: "/music/the-richest-man-in-babylon.webp",
        url: "https://open.spotify.com/album/7qJaVqhgiBtPLb9MOzwmZA",
      },
      {
        title: "( )",
        artist: "Sigur Rós",
        image: "/music/image-2.webp",
        url: "https://open.spotify.com/album/3FR8CV7OSyZDnxneavnh8t",
      },
    ],
  },
  {
    year: "2001",
    albums: [
      {
        title: "Is This It",
        artist: "The Strokes",
        image: "/music/is-this-it.webp",
        url: "https://open.spotify.com/album/2yNaksHgeMQM9Quse463b5",
      },
      {
        title: "The Glow, Pt. 2",
        artist: "The Microphones",
        image: "/music/the-glow-pt-2.webp",
        url: "https://open.spotify.com/album/6QYoRO2sXThCORAifrP4Bl",
      },
      {
        title: "Amelie from Montmartre (Original SoundTrack)",
        artist: "Yann Tiersen",
        image: "/music/amelie-from-montmartre-original-soundtrack.webp",
        url: "https://open.spotify.com/album/3QMOVTfwazGKLvyLq41pyV",
      },
      {
        title: "Simple Things",
        artist: "Zero 7",
        image: "/music/simple-things.webp",
        url: "https://open.spotify.com/album/1VRBB9iu84o3g16CczH9iH",
      },
      {
        title: "Rock Action",
        artist: "Mogwai",
        image: "/music/rock-action.webp",
        url: "https://open.spotify.com/album/4NbXiCf3b0Pqpl0YILc3S4",
      },
    ],
  },
  {
    year: "2000",
    albums: [
      {
        title: "Popless",
        artist: "GNR",
        image: "/music/popless.webp",
        url: "https://open.spotify.com/album/7GqnstFIZ7DeaL5P1zekyp",
      },
      {
        title: "Lift Your Skinny Fists Like Antennas to Heaven",
        artist: "Godspeed You! Black Emperor",
        image: "/music/lift-your-skinny-fists-like-antennas-to-heaven.webp",
        url: "https://open.spotify.com/album/2rT82YYlV9UoxBYLIezkRq",
      },
      {
        title: "Kid A",
        artist: "Radiohead",
        image: "/music/kid-a.webp",
        url: "https://open.spotify.com/album/19RUXBFyM4PpmrLRdtqWbp",
      },
      {
        title: "The Virgin Suicides (Deluxe Version - 15th Anniversary)",
        artist: "Air",
        image: "/music/the-virgin-suicides-deluxe-version-15th-anniversary.webp",
        url: "https://open.spotify.com/album/4ChzUkrMJVlmXpekFlJws5",
      },
    ],
  },
  {
    year: "1999",
    albums: [
      {
        title: "98.12.28 男達の別れ (Live)",
        artist: "Fishmans",
        image: "/music/98-12-28-live.webp",
        url: "https://open.spotify.com/album/5K4YFkTizFoMOyN5Khfp7G",
      },
      {
        title: "Ágætis byrjun",
        artist: "Sigur Rós",
        image: "/music/ag-tis-byrjun.webp",
        url: "https://open.spotify.com/album/1DMMv1Kmoli3Y9fVEZDUVC",
      },
      {
        title: "O Monstro Precisa De Amigos",
        artist: "Ornatos Violeta",
        image: "/music/o-monstro-precisa-de-amigos.webp",
        url: "https://open.spotify.com/album/1ctUX6jooPNVVKA8T6uNkz",
      },
      {
        title: "Jalamanta",
        artist: "Brant Bjork",
        image: "/music/jalamanta.webp",
        url: "https://open.spotify.com/album/36Lf0Mx1e57ogNhoY2ywv2",
      },
      {
        title: "Enema Of The State",
        artist: "blink-182",
        image: "/music/enema-of-the-state.webp",
        url: "https://open.spotify.com/album/1fF8kYX49s5Ufv4XEY5sjW",
      },
    ],
  },
  {
    year: "1998",
    albums: [
      {
        title: "Instrument Soundtrack",
        artist: "Fugazi",
        image: "/music/instrument-soundtrack.webp",
        url: "https://open.spotify.com/album/3tnzZhTTjRTExYc9odG0dt",
      },
      {
        title: "Moon Safari",
        artist: "Air",
        image: "/music/moon-safari.webp",
        url: "https://open.spotify.com/album/5dmYtZVJ1bG9RyrZBRrkOA",
      },
      {
        title: "Mezzanine",
        artist: "Massive Attack",
        image: "/music/mezzanine.webp",
        url: "https://open.spotify.com/album/49MNmJhZQewjt06rpwp6QR",
      },
      {
        title: "Big Calm",
        artist: "Morcheeba",
        image: "/music/big-calm.webp",
        url: "https://open.spotify.com/album/1ILnMWNKUXzcXug4Tq2JRP",
      },
      {
        title: "In the Aeroplane Over the Sea",
        artist: "Neutral Milk Hotel",
        image: "/music/in-the-aeroplane-over-the-sea.webp",
        url: "https://open.spotify.com/album/0vVekV45lOaVKs6RZQQNob",
      },
      {
        title: "Psyence Fiction",
        artist: "UNKLE",
        image: "/music/psyence-fiction.webp",
        url: "https://open.spotify.com/album/6Dxx0vxLQ83LK1PMZezlcY",
      },
      {
        title: "COWBOY BEBOP (Original Motion Picture Soundtrack)",
        artist: "SEATBELTS",
        image: "/music/cowboy-bebop-original-motion-picture-soundtrack.webp",
        url: "https://open.spotify.com/album/1XoE7ZirQ3gjxq8HIzTJU9",
      },
      {
        title: "Music Has The Right To Children",
        artist: "Boards of Canada",
        image: "/music/music-has-the-right-to-children.webp",
        url: "https://open.spotify.com/album/1vWnB0hYmluskQuzxwo25a",
      },
      {
        title: "TNT",
        artist: "Tortoise",
        image: "/music/tnt.webp",
        url: "https://open.spotify.com/album/4JwjxPyISbFEUeh267bYbg",
      },
    ],
  },
  {
    year: "1997",
    albums: [
      {
        title: "OK Computer",
        artist: "Radiohead",
        image: "/music/ok-computer.webp",
        url: "https://open.spotify.com/album/6dVIqQ8qmQ5GBnJ9shOYGE",
      },
      {
        title: "Ladies and gentlemen we are floating in space",
        artist: "Spiritualized",
        image: "/music/ladies-and-gentlemen-we-are-floating-in-space.webp",
        url: "https://open.spotify.com/album/56YzQ0dhmRMDryZsrjdHun",
      },
      {
        title: "O Melhor De António Variações",
        artist: "António Variações",
        image: "/music/o-melhor-de-antonio-variacoes.webp",
        url: "https://open.spotify.com/album/6UYUblITZs7VZf3pPhfQzJ",
      },
      {
        title: "A Grand Love Story",
        artist: "Kid Loco",
        image: "/music/a-grand-love-story.webp",
        url: "https://open.spotify.com/album/6R1VyRo1cFv2JDC1diCkPS",
      },
      {
        title: "Proud Like a God",
        artist: "Guano Apes",
        image: "/music/proud-like-a-god.webp",
        url: "https://open.spotify.com/album/1N5L209IqXQ6cqV2HFJU4G",
      },
    ],
  },
  {
    year: "1996",
    albums: [
      {
        title: "Soundtracks for the Blind",
        artist: "Swans",
        image: "/music/soundtracks-for-the-blind.webp",
        url: "https://open.spotify.com/album/7yV8WpwCChvzW3qr5MuzMf",
      },
      {
        title: "Tidal",
        artist: "Fiona Apple",
        image: "/music/tidal.webp",
        url: "https://open.spotify.com/album/5gVBXH8MT6zfdRkjp7qT18",
      },
      {
        title: "Ser Solidário",
        artist: "José Mário Branco",
        image: "/music/ser-solidario.webp",
        url: "https://open.spotify.com/album/4BU9W4qEpf2n04qpbEHAab",
      },
      {
        title: "Travelling Without Moving",
        artist: "Jamiroquai",
        image: "/music/travelling-without-moving.webp",
        url: "https://open.spotify.com/album/39j0mP1Vx1zRKMLMHhybw3",
      },
      {
        title: "If You're Feeling Sinister",
        artist: "Belle and Sebastian",
        image: "/music/if-you-re-feeling-sinister.webp",
        url: "https://play.spotify.com/album/4usPTyIIgnAZ9eiItfEYSK",
      },
    ],
  },
  {
    year: "1995",
    albums: [
      {
        title: "(What's the Story) Morning Glory?",
        artist: "Oasis",
        image: "/music/what-s-the-story-morning-glory.webp",
        url: "https://open.spotify.com/album/0PTVq4kaAAuROnfvfA7bHG",
      },
      {
        title: "Post",
        artist: "Björk",
        image: "/music/post.webp",
        url: "https://open.spotify.com/album/3p7WXDBxhC5KS9IFXnwae7",
      },
    ],
  },
  {
    year: "1994",
    albums: [
      {
        title: "Dummy",
        artist: "Portishead",
        image: "/music/dummy.webp",
        url: "https://open.spotify.com/album/3539EbNgIdEDGBKkUf4wno",
      },
      {
        title: "Selected Ambient Works Volume II",
        artist: "Aphex Twin",
        image: "/music/selected-ambient-works-volume-ii.webp",
        url: "https://open.spotify.com/album/17vHPMmoxN5B8cdhCDeMTe",
      },
      {
        title: "Souvlaki",
        artist: "Slowdive",
        image: "/music/souvlaki.webp",
        url: "https://open.spotify.com/album/4i21O3uVh5palcfFhCjlT7",
      },
    ],
  },
  {
    year: "1993",
    albums: [
      {
        title: "A lenda do Quarteto 1111",
        artist: "Quarteto 1111",
        image: "/music/a-lenda-do-quarteto-1111.webp",
        url: "https://open.spotify.com/album/2V3jB9Qty42D9OB14JgK3S",
      },
      {
        title: "Against Perfection",
        artist: "Adorable",
        image: "/music/against-perfection.webp",
        url: "https://open.spotify.com/album/2Mcs6yUdV7MkpQyCf8szkJ",
      },
      {
        title: "93 'til Infinity",
        artist: "Souls Of Mischief",
        image: "/music/93-til-infinity.webp",
        url: "https://open.spotify.com/album/7aSjaEi3OQ2aZemcJDhMb1",
      },
    ],
  },
  {
    year: "1992",
    albums: [
      {
        title: "Going Blank Again (Expanded)",
        artist: "Ride",
        image: "/music/going-blank-again-expanded.webp",
        url: "https://play.spotify.com/album/5l70cCHX1QzN680J68rblF",
      },
      {
        title: "Spooky",
        artist: "Lush",
        image: "/music/spooky.webp",
        url: "https://open.spotify.com/album/4sy5PYpO6j5BgLajSMGcZD",
      },
    ],
  },
  {
    year: "1991",
    albums: [
      {
        title: "loveless",
        artist: "my bloody valentine",
        image: "/music/loveless.webp",
        url: "https://open.spotify.com/album/3USQKOw0se5pBNEndu82Rb",
      },
    ],
  },
  {
    year: "1980s",
    albums: [
      {
        title: "13 Songs",
        artist: "Fugazi",
        image: "/music/13-songs.webp",
        url: "https://open.spotify.com/album/3tnzZhTTjRTExYc9odG0dt",
      },
      {
        title: "Caetanear",
        artist: "Caetano Veloso",
        image: "/music/caetanear.webp",
        url: "https://open.spotify.com/album/1vbnJI2hyuD8v6b2mGtQIl",
      },
      {
        title: "Apollo",
        artist: "Brian Eno",
        image: "/music/apollo.webp",
        url: "https://open.spotify.com/album/1Z2jkEtW5Sc9wWVxUgyG0E",
      },
      {
        title: "Volume Um",
        artist: "José Pinhal",
        image: "/music/volume-um.webp",
        url: "https://open.spotify.com/album/6pNyRkOYDA3GxpaFMXwNVN",
      },
      {
        title: "Psicopátria",
        artist: "GNR",
        image: "/music/psicopatria.webp",
        url: "https://open.spotify.com/album/3vbFmgbT27kgxQJr5lvpCo",
      },
    ],
  },
  {
    year: "1970s",
    albums: [
      {
        title: "10.000 Anos Depois Entre Vénus e Marte",
        artist: "José Cid",
        image: "/music/psicopatria.webp",
        url: "https://www.youtube.com/watch?v=otfChsCRGf8",
      },
      {
        title: "Onde Quando Como Porquê Cantamos Pessoas Vivas",
        artist: "Quarteto 1111",
        image: "/music/onde-quando-como-porque-cantamos-pessoas-vivas.webp",
        url: "https://open.spotify.com/album/5j52TsnHpqAHaPa1qEhkop",
      },
      {
        title: "Elis & Tom",
        artist: "Elis Regina, Antônio Carlos Jobim",
        image: "/music/elis-tom.webp",
        url: "https://open.spotify.com/album/3SE9n6EaVOJ81KA1KPLUWS",
      },
      {
        title: "The Dark Side Of The Moon",
        artist: "Pink Floyd",
        image: "/music/the-dark-side-of-the-moon.webp",
        url: "https://open.spotify.com/album/2WT1pbYjLJciAR26yMebkH",
      },
      {
        title: "Atom Heart Mother",
        artist: "Pink Floyd",
        image: "/music/atom-heart-mother.webp",
        url: "https://open.spotify.com/album/5c1ZTzT4oSkiiFS4wmEuOe",
      },
      {
        title: "華麗なるエレクトーン -ザ・ワード-",
        artist: "セキトオ・シゲオ",
        image: "/music/image.webp",
        url: "https://open.spotify.com/album/2rwQ71x5mXHX162ce5ypy7",
      },
      {
        title: "Fragile (Deluxe Edition)",
        artist: "Yes",
        image: "/music/fragile-deluxe-edition.webp",
        url: "https://open.spotify.com/album/0dZF93WHyOhTWjz5EWM7yG",
      },
      {
        title: "Maggot Brain",
        artist: "Funkadelic",
        image: "/music/maggot-brain.webp",
        url: "https://open.spotify.com/album/3ywVzrwMQ3Kq43N9zBdBQm",
      },
      {
        title: "Wish You Were Here",
        artist: "Pink Floyd",
        image: "/music/wish-you-were-here.webp",
        url: "https://open.spotify.com/album/6uvBKDGlJAYLH5Vy6RQVsc",
      },
    ],
  },
  {
    year: "1960s",
    albums: [
      {
        title: "The Velvet Underground & Nico 45th Anniversary",
        artist: "The Velvet Underground, Nico",
        image: "/music/the-velvet-underground-nico-45th-anniversary.webp",
        url: "https://open.spotify.com/album/4xwx0x7k6c5VuThz5qVqmV",
      },
      {
        title: "In The Court Of The Crimson King",
        artist: "King Crimson",
        image: "/music/in-the-court-of-the-crimson-king.webp",
        url: "https://open.spotify.com/album/6tVg2Wl9hVKMpHYcAl2V2M",
      },
      {
        title: "Samba Esquema Novo",
        artist: "Jorge Ben Jor",
        image: "/music/samba-esquema-novo.webp",
        url: "https://open.spotify.com/album/3xWp6y0HGsHZlXljNs7VRy",
      },
      {
        title: "Anatomy of a Murder",
        artist: "Duke Ellington",
        image: "/music/anatomy-of-a-murder.webp",
        url: "https://open.spotify.com/album/3WbMnT3abDjzrCzZQ9WtLK",
      },
    ],
  },
];
