import { readFile, writeFile } from "node:fs/promises";

const username = "afonsojramos";
const token = process.env.GITHUB_TOKEN;
const headers: Record<string, string> = {
  Accept: "application/vnd.github+json",
  "User-Agent": `${username}-portfolio`,
  "X-GitHub-Api-Version": "2022-11-28",
};

if (token) headers.Authorization = `Bearer ${token}`;

type SearchResponse = {
  total_count: number;
  items: Array<{ repository_url: string }>;
};

type RepositoryResponse = {
  full_name: string;
  html_url: string;
  stargazers_count: number;
};

type Contribution = {
  repository: string;
  url: string;
  stars: number;
  mergedPullRequests: number;
};

async function github<T>(path: string): Promise<T> {
  const response = await fetch(`https://api.github.com${path}`, { headers });

  if (!response.ok) {
    const message = await response.text();
    throw new Error(`GitHub API ${response.status} for ${path}: ${message}`);
  }

  return response.json() as Promise<T>;
}

const blacklistEntries = JSON.parse(
  await readFile(new URL("./contributions-blacklist.json", import.meta.url), "utf8"),
) as string[];
const blacklist = new Set(blacklistEntries);
const repositoryCounts = new Map<string, number>();
const query = encodeURIComponent(`type:pr author:${username} is:merged`);

for (let page = 1; ; page += 1) {
  // Pagination is intentionally sequential so the search rate limit is respected.
  // eslint-disable-next-line no-await-in-loop
  const result = await github<SearchResponse>(
    `/search/issues?q=${query}&per_page=100&page=${page}`,
  );

  for (const item of result.items) {
    const repository = item.repository_url.replace("https://api.github.com/repos/", "");
    repositoryCounts.set(repository, (repositoryCounts.get(repository) ?? 0) + 1);
  }

  if (page * 100 >= result.total_count || result.items.length === 0) break;
}

const candidates = [...repositoryCounts.entries()].filter(
  ([repository]) => !repository.toLowerCase().startsWith(`${username.toLowerCase()}/`),
);
const contributions: Contribution[] = [];

// Small batches avoid GitHub's secondary rate limit while keeping the refresh quick.
for (let index = 0; index < candidates.length; index += 10) {
  const batch = candidates.slice(index, index + 10);
  // Batches are intentionally sequential to avoid GitHub's secondary rate limit.
  // eslint-disable-next-line no-await-in-loop
  const repositories = await Promise.all(
    batch.map(async ([repository, mergedPullRequests]) => {
      const metadata = await github<RepositoryResponse>(`/repos/${repository}`);
      return {
        repository: metadata.full_name,
        url: metadata.html_url,
        stars: metadata.stargazers_count,
        mergedPullRequests,
      };
    }),
  );

  contributions.push(...repositories);
}

const visible = contributions
  .filter((entry) => !blacklist.has(entry.repository))
  .sort((a, b) => b.stars - a.stars || a.repository.localeCompare(b.repository));
const source =
  `// Generated by scripts/update-contributions.ts — do not edit by hand.\n` +
  `// Add repositories to scripts/contributions-blacklist.json to hide them.\n` +
  `export type Contribution = {\n` +
  `  repository: string;\n` +
  `  url: string;\n` +
  `  stars: number;\n` +
  `  mergedPullRequests: number;\n` +
  `};\n\n` +
  `export const contributions: Contribution[] = ${JSON.stringify(visible, null, 2)};\n`;

await writeFile(new URL("../src/content/contributions.ts", import.meta.url), source);
console.log(`Updated ${visible.length} repositories (${blacklist.size} blacklisted).`);
